/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
)

// checks if the Bond type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Bond{}

// Bond struct for Bond
type Bond struct {
	Id *string `json:"id,omitempty"`
	Kind *BondKind `json:"kind,omitempty"`
	CouponStartAt NullableTime `json:"coupon_start_at,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	FinalCouponAt NullableTime `json:"final_coupon_at,omitempty"`
	Isin *string `json:"isin,omitempty"`
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	Issuer *string `json:"issuer,omitempty"`
	MaturityAt *time.Time `json:"maturity_at,omitempty"`
	PrincipalValue *float64 `json:"principal_value,omitempty"`
	PaymentsPerYear *int32 `json:"payments_per_year,omitempty"`
	// Coupon payment frequency in nanoseconds (minimum 1000 i.e. 1 microsecond)
	PaymentsEvery *int32 `json:"payments_every,omitempty"`
	NextCouponPayment *time.Time `json:"next_coupon_payment,omitempty"`
}

// NewBond instantiates a new Bond object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBond() *Bond {
	this := Bond{}
	return &this
}

// NewBondWithDefaults instantiates a new Bond object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBondWithDefaults() *Bond {
	this := Bond{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Bond) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Bond) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Bond) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Bond) GetKind() BondKind {
	if o == nil || IsNil(o.Kind) {
		var ret BondKind
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetKindOk() (*BondKind, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Bond) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given BondKind and assigns it to the Kind field.
func (o *Bond) SetKind(v BondKind) {
	o.Kind = &v
}

// GetCouponStartAt returns the CouponStartAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Bond) GetCouponStartAt() time.Time {
	if o == nil || IsNil(o.CouponStartAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CouponStartAt.Get()
}

// GetCouponStartAtOk returns a tuple with the CouponStartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Bond) GetCouponStartAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CouponStartAt.Get(), o.CouponStartAt.IsSet()
}

// HasCouponStartAt returns a boolean if a field has been set.
func (o *Bond) HasCouponStartAt() bool {
	if o != nil && o.CouponStartAt.IsSet() {
		return true
	}

	return false
}

// SetCouponStartAt gets a reference to the given NullableTime and assigns it to the CouponStartAt field.
func (o *Bond) SetCouponStartAt(v time.Time) {
	o.CouponStartAt.Set(&v)
}
// SetCouponStartAtNil sets the value for CouponStartAt to be an explicit nil
func (o *Bond) SetCouponStartAtNil() {
	o.CouponStartAt.Set(nil)
}

// UnsetCouponStartAt ensures that no value is present for CouponStartAt, not even an explicit nil
func (o *Bond) UnsetCouponStartAt() {
	o.CouponStartAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Bond) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Bond) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Bond) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetFinalCouponAt returns the FinalCouponAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Bond) GetFinalCouponAt() time.Time {
	if o == nil || IsNil(o.FinalCouponAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.FinalCouponAt.Get()
}

// GetFinalCouponAtOk returns a tuple with the FinalCouponAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Bond) GetFinalCouponAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinalCouponAt.Get(), o.FinalCouponAt.IsSet()
}

// HasFinalCouponAt returns a boolean if a field has been set.
func (o *Bond) HasFinalCouponAt() bool {
	if o != nil && o.FinalCouponAt.IsSet() {
		return true
	}

	return false
}

// SetFinalCouponAt gets a reference to the given NullableTime and assigns it to the FinalCouponAt field.
func (o *Bond) SetFinalCouponAt(v time.Time) {
	o.FinalCouponAt.Set(&v)
}
// SetFinalCouponAtNil sets the value for FinalCouponAt to be an explicit nil
func (o *Bond) SetFinalCouponAtNil() {
	o.FinalCouponAt.Set(nil)
}

// UnsetFinalCouponAt ensures that no value is present for FinalCouponAt, not even an explicit nil
func (o *Bond) UnsetFinalCouponAt() {
	o.FinalCouponAt.Unset()
}

// GetIsin returns the Isin field value if set, zero value otherwise.
func (o *Bond) GetIsin() string {
	if o == nil || IsNil(o.Isin) {
		var ret string
		return ret
	}
	return *o.Isin
}

// GetIsinOk returns a tuple with the Isin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetIsinOk() (*string, bool) {
	if o == nil || IsNil(o.Isin) {
		return nil, false
	}
	return o.Isin, true
}

// HasIsin returns a boolean if a field has been set.
func (o *Bond) HasIsin() bool {
	if o != nil && !IsNil(o.Isin) {
		return true
	}

	return false
}

// SetIsin gets a reference to the given string and assigns it to the Isin field.
func (o *Bond) SetIsin(v string) {
	o.Isin = &v
}

// GetIssuedAt returns the IssuedAt field value if set, zero value otherwise.
func (o *Bond) GetIssuedAt() time.Time {
	if o == nil || IsNil(o.IssuedAt) {
		var ret time.Time
		return ret
	}
	return *o.IssuedAt
}

// GetIssuedAtOk returns a tuple with the IssuedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetIssuedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.IssuedAt) {
		return nil, false
	}
	return o.IssuedAt, true
}

// HasIssuedAt returns a boolean if a field has been set.
func (o *Bond) HasIssuedAt() bool {
	if o != nil && !IsNil(o.IssuedAt) {
		return true
	}

	return false
}

// SetIssuedAt gets a reference to the given time.Time and assigns it to the IssuedAt field.
func (o *Bond) SetIssuedAt(v time.Time) {
	o.IssuedAt = &v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *Bond) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *Bond) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *Bond) SetIssuer(v string) {
	o.Issuer = &v
}

// GetMaturityAt returns the MaturityAt field value if set, zero value otherwise.
func (o *Bond) GetMaturityAt() time.Time {
	if o == nil || IsNil(o.MaturityAt) {
		var ret time.Time
		return ret
	}
	return *o.MaturityAt
}

// GetMaturityAtOk returns a tuple with the MaturityAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetMaturityAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.MaturityAt) {
		return nil, false
	}
	return o.MaturityAt, true
}

// HasMaturityAt returns a boolean if a field has been set.
func (o *Bond) HasMaturityAt() bool {
	if o != nil && !IsNil(o.MaturityAt) {
		return true
	}

	return false
}

// SetMaturityAt gets a reference to the given time.Time and assigns it to the MaturityAt field.
func (o *Bond) SetMaturityAt(v time.Time) {
	o.MaturityAt = &v
}

// GetPrincipalValue returns the PrincipalValue field value if set, zero value otherwise.
func (o *Bond) GetPrincipalValue() float64 {
	if o == nil || IsNil(o.PrincipalValue) {
		var ret float64
		return ret
	}
	return *o.PrincipalValue
}

// GetPrincipalValueOk returns a tuple with the PrincipalValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetPrincipalValueOk() (*float64, bool) {
	if o == nil || IsNil(o.PrincipalValue) {
		return nil, false
	}
	return o.PrincipalValue, true
}

// HasPrincipalValue returns a boolean if a field has been set.
func (o *Bond) HasPrincipalValue() bool {
	if o != nil && !IsNil(o.PrincipalValue) {
		return true
	}

	return false
}

// SetPrincipalValue gets a reference to the given float64 and assigns it to the PrincipalValue field.
func (o *Bond) SetPrincipalValue(v float64) {
	o.PrincipalValue = &v
}

// GetPaymentsPerYear returns the PaymentsPerYear field value if set, zero value otherwise.
func (o *Bond) GetPaymentsPerYear() int32 {
	if o == nil || IsNil(o.PaymentsPerYear) {
		var ret int32
		return ret
	}
	return *o.PaymentsPerYear
}

// GetPaymentsPerYearOk returns a tuple with the PaymentsPerYear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetPaymentsPerYearOk() (*int32, bool) {
	if o == nil || IsNil(o.PaymentsPerYear) {
		return nil, false
	}
	return o.PaymentsPerYear, true
}

// HasPaymentsPerYear returns a boolean if a field has been set.
func (o *Bond) HasPaymentsPerYear() bool {
	if o != nil && !IsNil(o.PaymentsPerYear) {
		return true
	}

	return false
}

// SetPaymentsPerYear gets a reference to the given int32 and assigns it to the PaymentsPerYear field.
func (o *Bond) SetPaymentsPerYear(v int32) {
	o.PaymentsPerYear = &v
}

// GetPaymentsEvery returns the PaymentsEvery field value if set, zero value otherwise.
func (o *Bond) GetPaymentsEvery() int32 {
	if o == nil || IsNil(o.PaymentsEvery) {
		var ret int32
		return ret
	}
	return *o.PaymentsEvery
}

// GetPaymentsEveryOk returns a tuple with the PaymentsEvery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetPaymentsEveryOk() (*int32, bool) {
	if o == nil || IsNil(o.PaymentsEvery) {
		return nil, false
	}
	return o.PaymentsEvery, true
}

// HasPaymentsEvery returns a boolean if a field has been set.
func (o *Bond) HasPaymentsEvery() bool {
	if o != nil && !IsNil(o.PaymentsEvery) {
		return true
	}

	return false
}

// SetPaymentsEvery gets a reference to the given int32 and assigns it to the PaymentsEvery field.
func (o *Bond) SetPaymentsEvery(v int32) {
	o.PaymentsEvery = &v
}

// GetNextCouponPayment returns the NextCouponPayment field value if set, zero value otherwise.
func (o *Bond) GetNextCouponPayment() time.Time {
	if o == nil || IsNil(o.NextCouponPayment) {
		var ret time.Time
		return ret
	}
	return *o.NextCouponPayment
}

// GetNextCouponPaymentOk returns a tuple with the NextCouponPayment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetNextCouponPaymentOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextCouponPayment) {
		return nil, false
	}
	return o.NextCouponPayment, true
}

// HasNextCouponPayment returns a boolean if a field has been set.
func (o *Bond) HasNextCouponPayment() bool {
	if o != nil && !IsNil(o.NextCouponPayment) {
		return true
	}

	return false
}

// SetNextCouponPayment gets a reference to the given time.Time and assigns it to the NextCouponPayment field.
func (o *Bond) SetNextCouponPayment(v time.Time) {
	o.NextCouponPayment = &v
}

func (o Bond) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Bond) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if o.CouponStartAt.IsSet() {
		toSerialize["coupon_start_at"] = o.CouponStartAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.FinalCouponAt.IsSet() {
		toSerialize["final_coupon_at"] = o.FinalCouponAt.Get()
	}
	if !IsNil(o.Isin) {
		toSerialize["isin"] = o.Isin
	}
	if !IsNil(o.IssuedAt) {
		toSerialize["issued_at"] = o.IssuedAt
	}
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.MaturityAt) {
		toSerialize["maturity_at"] = o.MaturityAt
	}
	if !IsNil(o.PrincipalValue) {
		toSerialize["principal_value"] = o.PrincipalValue
	}
	if !IsNil(o.PaymentsPerYear) {
		toSerialize["payments_per_year"] = o.PaymentsPerYear
	}
	if !IsNil(o.PaymentsEvery) {
		toSerialize["payments_every"] = o.PaymentsEvery
	}
	if !IsNil(o.NextCouponPayment) {
		toSerialize["next_coupon_payment"] = o.NextCouponPayment
	}
	return toSerialize, nil
}

type NullableBond struct {
	value *Bond
	isSet bool
}

func (v NullableBond) Get() *Bond {
	return v.value
}

func (v *NullableBond) Set(val *Bond) {
	v.value = val
	v.isSet = true
}

func (v NullableBond) IsSet() bool {
	return v.isSet
}

func (v *NullableBond) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBond(val *Bond) *NullableBond {
	return &NullableBond{value: val, isSet: true}
}

func (v NullableBond) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBond) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


