/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the IsolatedCollateral type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsolatedCollateral{}

// IsolatedCollateral struct for IsolatedCollateral
type IsolatedCollateral struct {
	GlobalPositionId *string `json:"global_position_id,omitempty"`
	IsolatedPositionId *string `json:"isolated_position_id,omitempty"`
	TransactionId *string `json:"transaction_id,omitempty"`
	AssetId *string `json:"asset_id,omitempty"`
	Quantity *float64 `json:"quantity,omitempty"`
}

// NewIsolatedCollateral instantiates a new IsolatedCollateral object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsolatedCollateral() *IsolatedCollateral {
	this := IsolatedCollateral{}
	return &this
}

// NewIsolatedCollateralWithDefaults instantiates a new IsolatedCollateral object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsolatedCollateralWithDefaults() *IsolatedCollateral {
	this := IsolatedCollateral{}
	return &this
}

// GetGlobalPositionId returns the GlobalPositionId field value if set, zero value otherwise.
func (o *IsolatedCollateral) GetGlobalPositionId() string {
	if o == nil || IsNil(o.GlobalPositionId) {
		var ret string
		return ret
	}
	return *o.GlobalPositionId
}

// GetGlobalPositionIdOk returns a tuple with the GlobalPositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedCollateral) GetGlobalPositionIdOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalPositionId) {
		return nil, false
	}
	return o.GlobalPositionId, true
}

// HasGlobalPositionId returns a boolean if a field has been set.
func (o *IsolatedCollateral) HasGlobalPositionId() bool {
	if o != nil && !IsNil(o.GlobalPositionId) {
		return true
	}

	return false
}

// SetGlobalPositionId gets a reference to the given string and assigns it to the GlobalPositionId field.
func (o *IsolatedCollateral) SetGlobalPositionId(v string) {
	o.GlobalPositionId = &v
}

// GetIsolatedPositionId returns the IsolatedPositionId field value if set, zero value otherwise.
func (o *IsolatedCollateral) GetIsolatedPositionId() string {
	if o == nil || IsNil(o.IsolatedPositionId) {
		var ret string
		return ret
	}
	return *o.IsolatedPositionId
}

// GetIsolatedPositionIdOk returns a tuple with the IsolatedPositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedCollateral) GetIsolatedPositionIdOk() (*string, bool) {
	if o == nil || IsNil(o.IsolatedPositionId) {
		return nil, false
	}
	return o.IsolatedPositionId, true
}

// HasIsolatedPositionId returns a boolean if a field has been set.
func (o *IsolatedCollateral) HasIsolatedPositionId() bool {
	if o != nil && !IsNil(o.IsolatedPositionId) {
		return true
	}

	return false
}

// SetIsolatedPositionId gets a reference to the given string and assigns it to the IsolatedPositionId field.
func (o *IsolatedCollateral) SetIsolatedPositionId(v string) {
	o.IsolatedPositionId = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *IsolatedCollateral) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedCollateral) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *IsolatedCollateral) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *IsolatedCollateral) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *IsolatedCollateral) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedCollateral) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *IsolatedCollateral) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *IsolatedCollateral) SetAssetId(v string) {
	o.AssetId = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *IsolatedCollateral) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedCollateral) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *IsolatedCollateral) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *IsolatedCollateral) SetQuantity(v float64) {
	o.Quantity = &v
}

func (o IsolatedCollateral) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsolatedCollateral) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalPositionId) {
		toSerialize["global_position_id"] = o.GlobalPositionId
	}
	if !IsNil(o.IsolatedPositionId) {
		toSerialize["isolated_position_id"] = o.IsolatedPositionId
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullableIsolatedCollateral struct {
	value *IsolatedCollateral
	isSet bool
}

func (v NullableIsolatedCollateral) Get() *IsolatedCollateral {
	return v.value
}

func (v *NullableIsolatedCollateral) Set(val *IsolatedCollateral) {
	v.value = val
	v.isSet = true
}

func (v NullableIsolatedCollateral) IsSet() bool {
	return v.isSet
}

func (v *NullableIsolatedCollateral) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsolatedCollateral(val *IsolatedCollateral) *NullableIsolatedCollateral {
	return &NullableIsolatedCollateral{value: val, isSet: true}
}

func (v NullableIsolatedCollateral) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsolatedCollateral) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


