/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAssetYieldResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAssetYieldResponseEnvelope{}

// ListAssetYieldResponseEnvelope struct for ListAssetYieldResponseEnvelope
type ListAssetYieldResponseEnvelope struct {
	Data []AssetYield `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	// Metadata about the response, including status code and trace information.
	Metadata Metadata `json:"metadata"`
}

type _ListAssetYieldResponseEnvelope ListAssetYieldResponseEnvelope

// NewListAssetYieldResponseEnvelope instantiates a new ListAssetYieldResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAssetYieldResponseEnvelope(metadata Metadata) *ListAssetYieldResponseEnvelope {
	this := ListAssetYieldResponseEnvelope{}
	this.Metadata = metadata
	return &this
}

// NewListAssetYieldResponseEnvelopeWithDefaults instantiates a new ListAssetYieldResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAssetYieldResponseEnvelopeWithDefaults() *ListAssetYieldResponseEnvelope {
	this := ListAssetYieldResponseEnvelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListAssetYieldResponseEnvelope) GetData() []AssetYield {
	if o == nil || IsNil(o.Data) {
		var ret []AssetYield
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAssetYieldResponseEnvelope) GetDataOk() ([]AssetYield, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListAssetYieldResponseEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AssetYield and assigns it to the Data field.
func (o *ListAssetYieldResponseEnvelope) SetData(v []AssetYield) {
	o.Data = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ListAssetYieldResponseEnvelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAssetYieldResponseEnvelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ListAssetYieldResponseEnvelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ListAssetYieldResponseEnvelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value
func (o *ListAssetYieldResponseEnvelope) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ListAssetYieldResponseEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *ListAssetYieldResponseEnvelope) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o ListAssetYieldResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAssetYieldResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *ListAssetYieldResponseEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAssetYieldResponseEnvelope := _ListAssetYieldResponseEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAssetYieldResponseEnvelope)

	if err != nil {
		return err
	}

	*o = ListAssetYieldResponseEnvelope(varListAssetYieldResponseEnvelope)

	return err
}

type NullableListAssetYieldResponseEnvelope struct {
	value *ListAssetYieldResponseEnvelope
	isSet bool
}

func (v NullableListAssetYieldResponseEnvelope) Get() *ListAssetYieldResponseEnvelope {
	return v.value
}

func (v *NullableListAssetYieldResponseEnvelope) Set(val *ListAssetYieldResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableListAssetYieldResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableListAssetYieldResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAssetYieldResponseEnvelope(val *ListAssetYieldResponseEnvelope) *NullableListAssetYieldResponseEnvelope {
	return &NullableListAssetYieldResponseEnvelope{value: val, isSet: true}
}

func (v NullableListAssetYieldResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAssetYieldResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


