/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FeeQuoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeeQuoteResponse{}

// FeeQuoteResponse The estimated network fee to withdraw USDC via web3, alongside a signed, TTL-bound quote token the client submits with a later withdrawal so the server can validate the fee it was quoted.
type FeeQuoteResponse struct {
	// The withdrawal destination address, echoed from the request.
	To string `json:"to"`
	// Human-decimal USDC withdrawal quantity, echoed from the request.
	Quantity string `json:"quantity"`
	// The estimated network fee, in human USDC.
	Fee string `json:"fee"`
	// The estimated network fee, in micro-USDC base units.
	FeeBaseUnits string `json:"fee_base_units"`
	// EVM chain ID the quote was computed for.
	ChainId string `json:"chain_id"`
	// Signed, TTL-bound quote token to submit with a later withdrawal so the server can validate the fee it was quoted.
	QuoteToken string `json:"quote_token"`
	// When the quote token expires.
	ExpiresAt time.Time `json:"expires_at"`
}

type _FeeQuoteResponse FeeQuoteResponse

// NewFeeQuoteResponse instantiates a new FeeQuoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeeQuoteResponse(to string, quantity string, fee string, feeBaseUnits string, chainId string, quoteToken string, expiresAt time.Time) *FeeQuoteResponse {
	this := FeeQuoteResponse{}
	this.To = to
	this.Quantity = quantity
	this.Fee = fee
	this.FeeBaseUnits = feeBaseUnits
	this.ChainId = chainId
	this.QuoteToken = quoteToken
	this.ExpiresAt = expiresAt
	return &this
}

// NewFeeQuoteResponseWithDefaults instantiates a new FeeQuoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeeQuoteResponseWithDefaults() *FeeQuoteResponse {
	this := FeeQuoteResponse{}
	return &this
}

// GetTo returns the To field value
func (o *FeeQuoteResponse) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *FeeQuoteResponse) SetTo(v string) {
	o.To = v
}

// GetQuantity returns the Quantity field value
func (o *FeeQuoteResponse) GetQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *FeeQuoteResponse) SetQuantity(v string) {
	o.Quantity = v
}

// GetFee returns the Fee field value
func (o *FeeQuoteResponse) GetFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetFeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *FeeQuoteResponse) SetFee(v string) {
	o.Fee = v
}

// GetFeeBaseUnits returns the FeeBaseUnits field value
func (o *FeeQuoteResponse) GetFeeBaseUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeBaseUnits
}

// GetFeeBaseUnitsOk returns a tuple with the FeeBaseUnits field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetFeeBaseUnitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeBaseUnits, true
}

// SetFeeBaseUnits sets field value
func (o *FeeQuoteResponse) SetFeeBaseUnits(v string) {
	o.FeeBaseUnits = v
}

// GetChainId returns the ChainId field value
func (o *FeeQuoteResponse) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *FeeQuoteResponse) SetChainId(v string) {
	o.ChainId = v
}

// GetQuoteToken returns the QuoteToken field value
func (o *FeeQuoteResponse) GetQuoteToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteToken
}

// GetQuoteTokenOk returns a tuple with the QuoteToken field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetQuoteTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteToken, true
}

// SetQuoteToken sets field value
func (o *FeeQuoteResponse) SetQuoteToken(v string) {
	o.QuoteToken = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *FeeQuoteResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *FeeQuoteResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *FeeQuoteResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o FeeQuoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeeQuoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["to"] = o.To
	toSerialize["quantity"] = o.Quantity
	toSerialize["fee"] = o.Fee
	toSerialize["fee_base_units"] = o.FeeBaseUnits
	toSerialize["chain_id"] = o.ChainId
	toSerialize["quote_token"] = o.QuoteToken
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *FeeQuoteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"to",
		"quantity",
		"fee",
		"fee_base_units",
		"chain_id",
		"quote_token",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeeQuoteResponse := _FeeQuoteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFeeQuoteResponse)

	if err != nil {
		return err
	}

	*o = FeeQuoteResponse(varFeeQuoteResponse)

	return err
}

type NullableFeeQuoteResponse struct {
	value *FeeQuoteResponse
	isSet bool
}

func (v NullableFeeQuoteResponse) Get() *FeeQuoteResponse {
	return v.value
}

func (v *NullableFeeQuoteResponse) Set(val *FeeQuoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFeeQuoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFeeQuoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeeQuoteResponse(val *FeeQuoteResponse) *NullableFeeQuoteResponse {
	return &NullableFeeQuoteResponse{value: val, isSet: true}
}

func (v NullableFeeQuoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeeQuoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


