/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewIsolatedAccountResponseV2Envelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewIsolatedAccountResponseV2Envelope{}

// NewIsolatedAccountResponseV2Envelope struct for NewIsolatedAccountResponseV2Envelope
type NewIsolatedAccountResponseV2Envelope struct {
	Data *AccountV2 `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	// Metadata about the response, including status code and trace information.
	Metadata Metadata `json:"metadata"`
}

type _NewIsolatedAccountResponseV2Envelope NewIsolatedAccountResponseV2Envelope

// NewNewIsolatedAccountResponseV2Envelope instantiates a new NewIsolatedAccountResponseV2Envelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewIsolatedAccountResponseV2Envelope(metadata Metadata) *NewIsolatedAccountResponseV2Envelope {
	this := NewIsolatedAccountResponseV2Envelope{}
	this.Metadata = metadata
	return &this
}

// NewNewIsolatedAccountResponseV2EnvelopeWithDefaults instantiates a new NewIsolatedAccountResponseV2Envelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewIsolatedAccountResponseV2EnvelopeWithDefaults() *NewIsolatedAccountResponseV2Envelope {
	this := NewIsolatedAccountResponseV2Envelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NewIsolatedAccountResponseV2Envelope) GetData() AccountV2 {
	if o == nil || IsNil(o.Data) {
		var ret AccountV2
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewIsolatedAccountResponseV2Envelope) GetDataOk() (*AccountV2, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NewIsolatedAccountResponseV2Envelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AccountV2 and assigns it to the Data field.
func (o *NewIsolatedAccountResponseV2Envelope) SetData(v AccountV2) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NewIsolatedAccountResponseV2Envelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewIsolatedAccountResponseV2Envelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NewIsolatedAccountResponseV2Envelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *NewIsolatedAccountResponseV2Envelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value
func (o *NewIsolatedAccountResponseV2Envelope) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *NewIsolatedAccountResponseV2Envelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *NewIsolatedAccountResponseV2Envelope) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o NewIsolatedAccountResponseV2Envelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewIsolatedAccountResponseV2Envelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *NewIsolatedAccountResponseV2Envelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewIsolatedAccountResponseV2Envelope := _NewIsolatedAccountResponseV2Envelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewIsolatedAccountResponseV2Envelope)

	if err != nil {
		return err
	}

	*o = NewIsolatedAccountResponseV2Envelope(varNewIsolatedAccountResponseV2Envelope)

	return err
}

type NullableNewIsolatedAccountResponseV2Envelope struct {
	value *NewIsolatedAccountResponseV2Envelope
	isSet bool
}

func (v NullableNewIsolatedAccountResponseV2Envelope) Get() *NewIsolatedAccountResponseV2Envelope {
	return v.value
}

func (v *NullableNewIsolatedAccountResponseV2Envelope) Set(val *NewIsolatedAccountResponseV2Envelope) {
	v.value = val
	v.isSet = true
}

func (v NullableNewIsolatedAccountResponseV2Envelope) IsSet() bool {
	return v.isSet
}

func (v *NullableNewIsolatedAccountResponseV2Envelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewIsolatedAccountResponseV2Envelope(val *NewIsolatedAccountResponseV2Envelope) *NullableNewIsolatedAccountResponseV2Envelope {
	return &NullableNewIsolatedAccountResponseV2Envelope{value: val, isSet: true}
}

func (v NullableNewIsolatedAccountResponseV2Envelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewIsolatedAccountResponseV2Envelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


