/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Candle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Candle{}

// Candle struct for Candle
type Candle struct {
	OrderBookId string `json:"order_book_id"`
	StartTimestamp time.Time `json:"start_timestamp"`
	Open string `json:"open"`
	High string `json:"high"`
	Low string `json:"low"`
	Close string `json:"close"`
	// DEPRECATED: Use close_ytm instead.
	// Deprecated
	Ytm *string `json:"ytm,omitempty"`
	OpenYtm string `json:"open_ytm"`
	CloseYtm string `json:"close_ytm"`
	HighYtm string `json:"high_ytm"`
	LowYtm string `json:"low_ytm"`
	Volume string `json:"volume"`
}

type _Candle Candle

// NewCandle instantiates a new Candle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCandle(orderBookId string, startTimestamp time.Time, open string, high string, low string, close string, openYtm string, closeYtm string, highYtm string, lowYtm string, volume string) *Candle {
	this := Candle{}
	this.OrderBookId = orderBookId
	this.StartTimestamp = startTimestamp
	this.Open = open
	this.High = high
	this.Low = low
	this.Close = close
	this.OpenYtm = openYtm
	this.CloseYtm = closeYtm
	this.HighYtm = highYtm
	this.LowYtm = lowYtm
	this.Volume = volume
	return &this
}

// NewCandleWithDefaults instantiates a new Candle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCandleWithDefaults() *Candle {
	this := Candle{}
	return &this
}

// GetOrderBookId returns the OrderBookId field value
func (o *Candle) GetOrderBookId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderBookId
}

// GetOrderBookIdOk returns a tuple with the OrderBookId field value
// and a boolean to check if the value has been set.
func (o *Candle) GetOrderBookIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderBookId, true
}

// SetOrderBookId sets field value
func (o *Candle) SetOrderBookId(v string) {
	o.OrderBookId = v
}

// GetStartTimestamp returns the StartTimestamp field value
func (o *Candle) GetStartTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value
// and a boolean to check if the value has been set.
func (o *Candle) GetStartTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimestamp, true
}

// SetStartTimestamp sets field value
func (o *Candle) SetStartTimestamp(v time.Time) {
	o.StartTimestamp = v
}

// GetOpen returns the Open field value
func (o *Candle) GetOpen() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Open
}

// GetOpenOk returns a tuple with the Open field value
// and a boolean to check if the value has been set.
func (o *Candle) GetOpenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Open, true
}

// SetOpen sets field value
func (o *Candle) SetOpen(v string) {
	o.Open = v
}

// GetHigh returns the High field value
func (o *Candle) GetHigh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.High
}

// GetHighOk returns a tuple with the High field value
// and a boolean to check if the value has been set.
func (o *Candle) GetHighOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.High, true
}

// SetHigh sets field value
func (o *Candle) SetHigh(v string) {
	o.High = v
}

// GetLow returns the Low field value
func (o *Candle) GetLow() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Low
}

// GetLowOk returns a tuple with the Low field value
// and a boolean to check if the value has been set.
func (o *Candle) GetLowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Low, true
}

// SetLow sets field value
func (o *Candle) SetLow(v string) {
	o.Low = v
}

// GetClose returns the Close field value
func (o *Candle) GetClose() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Close
}

// GetCloseOk returns a tuple with the Close field value
// and a boolean to check if the value has been set.
func (o *Candle) GetCloseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Close, true
}

// SetClose sets field value
func (o *Candle) SetClose(v string) {
	o.Close = v
}

// GetYtm returns the Ytm field value if set, zero value otherwise.
// Deprecated
func (o *Candle) GetYtm() string {
	if o == nil || IsNil(o.Ytm) {
		var ret string
		return ret
	}
	return *o.Ytm
}

// GetYtmOk returns a tuple with the Ytm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *Candle) GetYtmOk() (*string, bool) {
	if o == nil || IsNil(o.Ytm) {
		return nil, false
	}
	return o.Ytm, true
}

// HasYtm returns a boolean if a field has been set.
func (o *Candle) HasYtm() bool {
	if o != nil && !IsNil(o.Ytm) {
		return true
	}

	return false
}

// SetYtm gets a reference to the given string and assigns it to the Ytm field.
// Deprecated
func (o *Candle) SetYtm(v string) {
	o.Ytm = &v
}

// GetOpenYtm returns the OpenYtm field value
func (o *Candle) GetOpenYtm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OpenYtm
}

// GetOpenYtmOk returns a tuple with the OpenYtm field value
// and a boolean to check if the value has been set.
func (o *Candle) GetOpenYtmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpenYtm, true
}

// SetOpenYtm sets field value
func (o *Candle) SetOpenYtm(v string) {
	o.OpenYtm = v
}

// GetCloseYtm returns the CloseYtm field value
func (o *Candle) GetCloseYtm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloseYtm
}

// GetCloseYtmOk returns a tuple with the CloseYtm field value
// and a boolean to check if the value has been set.
func (o *Candle) GetCloseYtmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloseYtm, true
}

// SetCloseYtm sets field value
func (o *Candle) SetCloseYtm(v string) {
	o.CloseYtm = v
}

// GetHighYtm returns the HighYtm field value
func (o *Candle) GetHighYtm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HighYtm
}

// GetHighYtmOk returns a tuple with the HighYtm field value
// and a boolean to check if the value has been set.
func (o *Candle) GetHighYtmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HighYtm, true
}

// SetHighYtm sets field value
func (o *Candle) SetHighYtm(v string) {
	o.HighYtm = v
}

// GetLowYtm returns the LowYtm field value
func (o *Candle) GetLowYtm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LowYtm
}

// GetLowYtmOk returns a tuple with the LowYtm field value
// and a boolean to check if the value has been set.
func (o *Candle) GetLowYtmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LowYtm, true
}

// SetLowYtm sets field value
func (o *Candle) SetLowYtm(v string) {
	o.LowYtm = v
}

// GetVolume returns the Volume field value
func (o *Candle) GetVolume() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *Candle) GetVolumeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *Candle) SetVolume(v string) {
	o.Volume = v
}

func (o Candle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Candle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order_book_id"] = o.OrderBookId
	toSerialize["start_timestamp"] = o.StartTimestamp
	toSerialize["open"] = o.Open
	toSerialize["high"] = o.High
	toSerialize["low"] = o.Low
	toSerialize["close"] = o.Close
	if !IsNil(o.Ytm) {
		toSerialize["ytm"] = o.Ytm
	}
	toSerialize["open_ytm"] = o.OpenYtm
	toSerialize["close_ytm"] = o.CloseYtm
	toSerialize["high_ytm"] = o.HighYtm
	toSerialize["low_ytm"] = o.LowYtm
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

func (o *Candle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order_book_id",
		"start_timestamp",
		"open",
		"high",
		"low",
		"close",
		"open_ytm",
		"close_ytm",
		"high_ytm",
		"low_ytm",
		"volume",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCandle := _Candle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCandle)

	if err != nil {
		return err
	}

	*o = Candle(varCandle)

	return err
}

type NullableCandle struct {
	value *Candle
	isSet bool
}

func (v NullableCandle) Get() *Candle {
	return v.value
}

func (v *NullableCandle) Set(val *Candle) {
	v.value = val
	v.isSet = true
}

func (v NullableCandle) IsSet() bool {
	return v.isSet
}

func (v *NullableCandle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCandle(val *Candle) *NullableCandle {
	return &NullableCandle{value: val, isSet: true}
}

func (v NullableCandle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCandle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


