/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient
import (
	"time"
)

type Transaction struct {
	Id string `json:"id,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	Kind *TransactionKind `json:"kind,omitempty"`
	Asset0 string `json:"asset0,omitempty"`
	Quantity0 string `json:"quantity0,omitempty"`
	Quantity1 string `json:"quantity1,omitempty"`
	Asset1 string `json:"asset1,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
