/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient
import (
	"time"
)

type StreamTradesEntry struct {
	Val *Trade `json:"Val,omitempty"`
	// The timestamp when the data was created
	Time time.Time `json:"Time,omitempty"`
}
