/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransferBalancesResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferBalancesResponseEnvelope{}

// TransferBalancesResponseEnvelope struct for TransferBalancesResponseEnvelope
type TransferBalancesResponseEnvelope struct {
	Data *BalanceTransfer `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	// Metadata about the response, including status code and trace information.
	Metadata Metadata `json:"metadata"`
}

type _TransferBalancesResponseEnvelope TransferBalancesResponseEnvelope

// NewTransferBalancesResponseEnvelope instantiates a new TransferBalancesResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferBalancesResponseEnvelope(metadata Metadata) *TransferBalancesResponseEnvelope {
	this := TransferBalancesResponseEnvelope{}
	this.Metadata = metadata
	return &this
}

// NewTransferBalancesResponseEnvelopeWithDefaults instantiates a new TransferBalancesResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferBalancesResponseEnvelopeWithDefaults() *TransferBalancesResponseEnvelope {
	this := TransferBalancesResponseEnvelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TransferBalancesResponseEnvelope) GetData() BalanceTransfer {
	if o == nil || IsNil(o.Data) {
		var ret BalanceTransfer
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferBalancesResponseEnvelope) GetDataOk() (*BalanceTransfer, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TransferBalancesResponseEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given BalanceTransfer and assigns it to the Data field.
func (o *TransferBalancesResponseEnvelope) SetData(v BalanceTransfer) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TransferBalancesResponseEnvelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferBalancesResponseEnvelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TransferBalancesResponseEnvelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *TransferBalancesResponseEnvelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value
func (o *TransferBalancesResponseEnvelope) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *TransferBalancesResponseEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *TransferBalancesResponseEnvelope) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o TransferBalancesResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferBalancesResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *TransferBalancesResponseEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferBalancesResponseEnvelope := _TransferBalancesResponseEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferBalancesResponseEnvelope)

	if err != nil {
		return err
	}

	*o = TransferBalancesResponseEnvelope(varTransferBalancesResponseEnvelope)

	return err
}

type NullableTransferBalancesResponseEnvelope struct {
	value *TransferBalancesResponseEnvelope
	isSet bool
}

func (v NullableTransferBalancesResponseEnvelope) Get() *TransferBalancesResponseEnvelope {
	return v.value
}

func (v *NullableTransferBalancesResponseEnvelope) Set(val *TransferBalancesResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferBalancesResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferBalancesResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferBalancesResponseEnvelope(val *TransferBalancesResponseEnvelope) *NullableTransferBalancesResponseEnvelope {
	return &NullableTransferBalancesResponseEnvelope{value: val, isSet: true}
}

func (v NullableTransferBalancesResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferBalancesResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


