/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PromoLinkListResponseAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromoLinkListResponseAllOfData{}

// PromoLinkListResponseAllOfData struct for PromoLinkListResponseAllOfData
type PromoLinkListResponseAllOfData struct {
	Links []PromoLinkAdmin `json:"links"`
	// Opaque unpadded base64url keyset cursor.
	NextCursor *string `json:"next_cursor,omitempty"`
}

type _PromoLinkListResponseAllOfData PromoLinkListResponseAllOfData

// NewPromoLinkListResponseAllOfData instantiates a new PromoLinkListResponseAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromoLinkListResponseAllOfData(links []PromoLinkAdmin) *PromoLinkListResponseAllOfData {
	this := PromoLinkListResponseAllOfData{}
	this.Links = links
	return &this
}

// NewPromoLinkListResponseAllOfDataWithDefaults instantiates a new PromoLinkListResponseAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromoLinkListResponseAllOfDataWithDefaults() *PromoLinkListResponseAllOfData {
	this := PromoLinkListResponseAllOfData{}
	return &this
}

// GetLinks returns the Links field value
func (o *PromoLinkListResponseAllOfData) GetLinks() []PromoLinkAdmin {
	if o == nil {
		var ret []PromoLinkAdmin
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *PromoLinkListResponseAllOfData) GetLinksOk() ([]PromoLinkAdmin, bool) {
	if o == nil {
		return nil, false
	}
	return o.Links, true
}

// SetLinks sets field value
func (o *PromoLinkListResponseAllOfData) SetLinks(v []PromoLinkAdmin) {
	o.Links = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *PromoLinkListResponseAllOfData) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoLinkListResponseAllOfData) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *PromoLinkListResponseAllOfData) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *PromoLinkListResponseAllOfData) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o PromoLinkListResponseAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromoLinkListResponseAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	return toSerialize, nil
}

func (o *PromoLinkListResponseAllOfData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromoLinkListResponseAllOfData := _PromoLinkListResponseAllOfData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromoLinkListResponseAllOfData)

	if err != nil {
		return err
	}

	*o = PromoLinkListResponseAllOfData(varPromoLinkListResponseAllOfData)

	return err
}

type NullablePromoLinkListResponseAllOfData struct {
	value *PromoLinkListResponseAllOfData
	isSet bool
}

func (v NullablePromoLinkListResponseAllOfData) Get() *PromoLinkListResponseAllOfData {
	return v.value
}

func (v *NullablePromoLinkListResponseAllOfData) Set(val *PromoLinkListResponseAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullablePromoLinkListResponseAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullablePromoLinkListResponseAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromoLinkListResponseAllOfData(val *PromoLinkListResponseAllOfData) *NullablePromoLinkListResponseAllOfData {
	return &NullablePromoLinkListResponseAllOfData{value: val, isSet: true}
}

func (v NullablePromoLinkListResponseAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromoLinkListResponseAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


