/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAPIKeyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAPIKeyData{}

// CreateAPIKeyData struct for CreateAPIKeyData
type CreateAPIKeyData struct {
	KeyId string `json:"key_id"`
	ApiKey string `json:"api_key"`
	Label string `json:"label"`
}

type _CreateAPIKeyData CreateAPIKeyData

// NewCreateAPIKeyData instantiates a new CreateAPIKeyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAPIKeyData(keyId string, apiKey string, label string) *CreateAPIKeyData {
	this := CreateAPIKeyData{}
	this.KeyId = keyId
	this.ApiKey = apiKey
	this.Label = label
	return &this
}

// NewCreateAPIKeyDataWithDefaults instantiates a new CreateAPIKeyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAPIKeyDataWithDefaults() *CreateAPIKeyData {
	this := CreateAPIKeyData{}
	return &this
}

// GetKeyId returns the KeyId field value
func (o *CreateAPIKeyData) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyData) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *CreateAPIKeyData) SetKeyId(v string) {
	o.KeyId = v
}

// GetApiKey returns the ApiKey field value
func (o *CreateAPIKeyData) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyData) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *CreateAPIKeyData) SetApiKey(v string) {
	o.ApiKey = v
}

// GetLabel returns the Label field value
func (o *CreateAPIKeyData) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyData) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *CreateAPIKeyData) SetLabel(v string) {
	o.Label = v
}

func (o CreateAPIKeyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAPIKeyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_id"] = o.KeyId
	toSerialize["api_key"] = o.ApiKey
	toSerialize["label"] = o.Label
	return toSerialize, nil
}

func (o *CreateAPIKeyData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_id",
		"api_key",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAPIKeyData := _CreateAPIKeyData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAPIKeyData)

	if err != nil {
		return err
	}

	*o = CreateAPIKeyData(varCreateAPIKeyData)

	return err
}

type NullableCreateAPIKeyData struct {
	value *CreateAPIKeyData
	isSet bool
}

func (v NullableCreateAPIKeyData) Get() *CreateAPIKeyData {
	return v.value
}

func (v *NullableCreateAPIKeyData) Set(val *CreateAPIKeyData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAPIKeyData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAPIKeyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAPIKeyData(val *CreateAPIKeyData) *NullableCreateAPIKeyData {
	return &NullableCreateAPIKeyData{value: val, isSet: true}
}

func (v NullableCreateAPIKeyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAPIKeyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


