/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type OrderBookBalance struct {
	// The ID of the order book.
	OrderBookId string `json:"order_book_id,omitempty"`
	// The quantity of the base asset.
	BaseQuantity float64 `json:"base_quantity,omitempty"`
	// The quantity of the quote asset.
	QuoteQuantity float64 `json:"quote_quantity,omitempty"`
	// The quantity of pool shares.
	SharesQuantity float64 `json:"shares_quantity,omitempty"`
}
