/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IssuedPromoLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuedPromoLink{}

// IssuedPromoLink struct for IssuedPromoLink
type IssuedPromoLink struct {
	Id string `json:"id"`
	TokenPrefix string `json:"token_prefix"`
	// Private claim URL. Do not log or cache.
	Url string `json:"url"`
	QrUrl string `json:"qr_url"`
	ExpiresAt time.Time `json:"expires_at"`
}

type _IssuedPromoLink IssuedPromoLink

// NewIssuedPromoLink instantiates a new IssuedPromoLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuedPromoLink(id string, tokenPrefix string, url string, qrUrl string, expiresAt time.Time) *IssuedPromoLink {
	this := IssuedPromoLink{}
	this.Id = id
	this.TokenPrefix = tokenPrefix
	this.Url = url
	this.QrUrl = qrUrl
	this.ExpiresAt = expiresAt
	return &this
}

// NewIssuedPromoLinkWithDefaults instantiates a new IssuedPromoLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuedPromoLinkWithDefaults() *IssuedPromoLink {
	this := IssuedPromoLink{}
	return &this
}

// GetId returns the Id field value
func (o *IssuedPromoLink) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IssuedPromoLink) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IssuedPromoLink) SetId(v string) {
	o.Id = v
}

// GetTokenPrefix returns the TokenPrefix field value
func (o *IssuedPromoLink) GetTokenPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenPrefix
}

// GetTokenPrefixOk returns a tuple with the TokenPrefix field value
// and a boolean to check if the value has been set.
func (o *IssuedPromoLink) GetTokenPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenPrefix, true
}

// SetTokenPrefix sets field value
func (o *IssuedPromoLink) SetTokenPrefix(v string) {
	o.TokenPrefix = v
}

// GetUrl returns the Url field value
func (o *IssuedPromoLink) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *IssuedPromoLink) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *IssuedPromoLink) SetUrl(v string) {
	o.Url = v
}

// GetQrUrl returns the QrUrl field value
func (o *IssuedPromoLink) GetQrUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QrUrl
}

// GetQrUrlOk returns a tuple with the QrUrl field value
// and a boolean to check if the value has been set.
func (o *IssuedPromoLink) GetQrUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QrUrl, true
}

// SetQrUrl sets field value
func (o *IssuedPromoLink) SetQrUrl(v string) {
	o.QrUrl = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *IssuedPromoLink) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *IssuedPromoLink) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *IssuedPromoLink) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o IssuedPromoLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuedPromoLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["token_prefix"] = o.TokenPrefix
	toSerialize["url"] = o.Url
	toSerialize["qr_url"] = o.QrUrl
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *IssuedPromoLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"token_prefix",
		"url",
		"qr_url",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIssuedPromoLink := _IssuedPromoLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIssuedPromoLink)

	if err != nil {
		return err
	}

	*o = IssuedPromoLink(varIssuedPromoLink)

	return err
}

type NullableIssuedPromoLink struct {
	value *IssuedPromoLink
	isSet bool
}

func (v NullableIssuedPromoLink) Get() *IssuedPromoLink {
	return v.value
}

func (v *NullableIssuedPromoLink) Set(val *IssuedPromoLink) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuedPromoLink) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuedPromoLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuedPromoLink(val *IssuedPromoLink) *NullableIssuedPromoLink {
	return &NullableIssuedPromoLink{value: val, isSet: true}
}

func (v NullableIssuedPromoLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuedPromoLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


