/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the OrderBookHaltResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderBookHaltResponseEnvelope{}

// OrderBookHaltResponseEnvelope struct for OrderBookHaltResponseEnvelope
type OrderBookHaltResponseEnvelope struct {
	Data *bool `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	Metadata *Metadata `json:"metadata,omitempty"`
}

// NewOrderBookHaltResponseEnvelope instantiates a new OrderBookHaltResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderBookHaltResponseEnvelope() *OrderBookHaltResponseEnvelope {
	this := OrderBookHaltResponseEnvelope{}
	return &this
}

// NewOrderBookHaltResponseEnvelopeWithDefaults instantiates a new OrderBookHaltResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderBookHaltResponseEnvelopeWithDefaults() *OrderBookHaltResponseEnvelope {
	this := OrderBookHaltResponseEnvelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OrderBookHaltResponseEnvelope) GetData() bool {
	if o == nil || IsNil(o.Data) {
		var ret bool
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBookHaltResponseEnvelope) GetDataOk() (*bool, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OrderBookHaltResponseEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given bool and assigns it to the Data field.
func (o *OrderBookHaltResponseEnvelope) SetData(v bool) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *OrderBookHaltResponseEnvelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBookHaltResponseEnvelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *OrderBookHaltResponseEnvelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *OrderBookHaltResponseEnvelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OrderBookHaltResponseEnvelope) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBookHaltResponseEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OrderBookHaltResponseEnvelope) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *OrderBookHaltResponseEnvelope) SetMetadata(v Metadata) {
	o.Metadata = &v
}

func (o OrderBookHaltResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderBookHaltResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableOrderBookHaltResponseEnvelope struct {
	value *OrderBookHaltResponseEnvelope
	isSet bool
}

func (v NullableOrderBookHaltResponseEnvelope) Get() *OrderBookHaltResponseEnvelope {
	return v.value
}

func (v *NullableOrderBookHaltResponseEnvelope) Set(val *OrderBookHaltResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderBookHaltResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderBookHaltResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderBookHaltResponseEnvelope(val *OrderBookHaltResponseEnvelope) *NullableOrderBookHaltResponseEnvelope {
	return &NullableOrderBookHaltResponseEnvelope{value: val, isSet: true}
}

func (v NullableOrderBookHaltResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderBookHaltResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


