/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserCouponPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCouponPayment{}

// UserCouponPayment struct for UserCouponPayment
type UserCouponPayment struct {
	UserId string `json:"user_id"`
	PositionId string `json:"position_id"`
	AssetId string `json:"asset_id"`
	CouponPaymentId string `json:"coupon_payment_id"`
	Seq int64 `json:"seq"`
	Pending string `json:"pending"`
	Completed string `json:"completed"`
	StartedAt time.Time `json:"started_at"`
	EndedAt time.Time `json:"ended_at"`
	TransactionId *string `json:"transaction_id,omitempty"`
}

type _UserCouponPayment UserCouponPayment

// NewUserCouponPayment instantiates a new UserCouponPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCouponPayment(userId string, positionId string, assetId string, couponPaymentId string, seq int64, pending string, completed string, startedAt time.Time, endedAt time.Time) *UserCouponPayment {
	this := UserCouponPayment{}
	this.UserId = userId
	this.PositionId = positionId
	this.AssetId = assetId
	this.CouponPaymentId = couponPaymentId
	this.Seq = seq
	this.Pending = pending
	this.Completed = completed
	this.StartedAt = startedAt
	this.EndedAt = endedAt
	return &this
}

// NewUserCouponPaymentWithDefaults instantiates a new UserCouponPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCouponPaymentWithDefaults() *UserCouponPayment {
	this := UserCouponPayment{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UserCouponPayment) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserCouponPayment) SetUserId(v string) {
	o.UserId = v
}

// GetPositionId returns the PositionId field value
func (o *UserCouponPayment) GetPositionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetPositionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionId, true
}

// SetPositionId sets field value
func (o *UserCouponPayment) SetPositionId(v string) {
	o.PositionId = v
}

// GetAssetId returns the AssetId field value
func (o *UserCouponPayment) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *UserCouponPayment) SetAssetId(v string) {
	o.AssetId = v
}

// GetCouponPaymentId returns the CouponPaymentId field value
func (o *UserCouponPayment) GetCouponPaymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CouponPaymentId
}

// GetCouponPaymentIdOk returns a tuple with the CouponPaymentId field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetCouponPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CouponPaymentId, true
}

// SetCouponPaymentId sets field value
func (o *UserCouponPayment) SetCouponPaymentId(v string) {
	o.CouponPaymentId = v
}

// GetSeq returns the Seq field value
func (o *UserCouponPayment) GetSeq() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Seq
}

// GetSeqOk returns a tuple with the Seq field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetSeqOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seq, true
}

// SetSeq sets field value
func (o *UserCouponPayment) SetSeq(v int64) {
	o.Seq = v
}

// GetPending returns the Pending field value
func (o *UserCouponPayment) GetPending() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetPendingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pending, true
}

// SetPending sets field value
func (o *UserCouponPayment) SetPending(v string) {
	o.Pending = v
}

// GetCompleted returns the Completed field value
func (o *UserCouponPayment) GetCompleted() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetCompletedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Completed, true
}

// SetCompleted sets field value
func (o *UserCouponPayment) SetCompleted(v string) {
	o.Completed = v
}

// GetStartedAt returns the StartedAt field value
func (o *UserCouponPayment) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *UserCouponPayment) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetEndedAt returns the EndedAt field value
func (o *UserCouponPayment) GetEndedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetEndedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndedAt, true
}

// SetEndedAt sets field value
func (o *UserCouponPayment) SetEndedAt(v time.Time) {
	o.EndedAt = v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *UserCouponPayment) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCouponPayment) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *UserCouponPayment) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *UserCouponPayment) SetTransactionId(v string) {
	o.TransactionId = &v
}

func (o UserCouponPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCouponPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["position_id"] = o.PositionId
	toSerialize["asset_id"] = o.AssetId
	toSerialize["coupon_payment_id"] = o.CouponPaymentId
	toSerialize["seq"] = o.Seq
	toSerialize["pending"] = o.Pending
	toSerialize["completed"] = o.Completed
	toSerialize["started_at"] = o.StartedAt
	toSerialize["ended_at"] = o.EndedAt
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	return toSerialize, nil
}

func (o *UserCouponPayment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"position_id",
		"asset_id",
		"coupon_payment_id",
		"seq",
		"pending",
		"completed",
		"started_at",
		"ended_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserCouponPayment := _UserCouponPayment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserCouponPayment)

	if err != nil {
		return err
	}

	*o = UserCouponPayment(varUserCouponPayment)

	return err
}

type NullableUserCouponPayment struct {
	value *UserCouponPayment
	isSet bool
}

func (v NullableUserCouponPayment) Get() *UserCouponPayment {
	return v.value
}

func (v *NullableUserCouponPayment) Set(val *UserCouponPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCouponPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCouponPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCouponPayment(val *UserCouponPayment) *NullableUserCouponPayment {
	return &NullableUserCouponPayment{value: val, isSet: true}
}

func (v NullableUserCouponPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCouponPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


