/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserInterest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInterest{}

// UserInterest struct for UserInterest
type UserInterest struct {
	Available map[string]int32 `json:"available"`
	Value map[string]string `json:"value"`
}

type _UserInterest UserInterest

// NewUserInterest instantiates a new UserInterest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInterest(available map[string]int32, value map[string]string) *UserInterest {
	this := UserInterest{}
	this.Available = available
	this.Value = value
	return &this
}

// NewUserInterestWithDefaults instantiates a new UserInterest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInterestWithDefaults() *UserInterest {
	this := UserInterest{}
	return &this
}

// GetAvailable returns the Available field value
func (o *UserInterest) GetAvailable() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *UserInterest) GetAvailableOk() (map[string]int32, bool) {
	if o == nil {
		return map[string]int32{}, false
	}
	return o.Available, true
}

// SetAvailable sets field value
func (o *UserInterest) SetAvailable(v map[string]int32) {
	o.Available = v
}

// GetValue returns the Value field value
func (o *UserInterest) GetValue() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UserInterest) GetValueOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *UserInterest) SetValue(v map[string]string) {
	o.Value = v
}

func (o UserInterest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInterest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["available"] = o.Available
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *UserInterest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"available",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserInterest := _UserInterest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserInterest)

	if err != nil {
		return err
	}

	*o = UserInterest(varUserInterest)

	return err
}

type NullableUserInterest struct {
	value *UserInterest
	isSet bool
}

func (v NullableUserInterest) Get() *UserInterest {
	return v.value
}

func (v *NullableUserInterest) Set(val *UserInterest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInterest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInterest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInterest(val *UserInterest) *NullableUserInterest {
	return &NullableUserInterest{value: val, isSet: true}
}

func (v NullableUserInterest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInterest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


