/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
)

// checks if the CouponPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CouponPayment{}

// CouponPayment struct for CouponPayment
type CouponPayment struct {
	Id *string `json:"id,omitempty"`
	AssetId *string `json:"asset_id,omitempty"`
	Yield *float32 `json:"yield,omitempty"`
	StartAt *time.Time `json:"start_at,omitempty"`
	EndAt *time.Time `json:"end_at,omitempty"`
	PayAt *time.Time `json:"pay_at,omitempty"`
	AvailableToPay *float64 `json:"available_to_pay,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Number of nanoseconds to wait between coupon payment processing, must be at least 1000 (1 microsecond)
	ProcessEvery *int32 `json:"process_every,omitempty"`
	LastProcessedAt *time.Time `json:"last_processed_at,omitempty"`
}

// NewCouponPayment instantiates a new CouponPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCouponPayment() *CouponPayment {
	this := CouponPayment{}
	return &this
}

// NewCouponPaymentWithDefaults instantiates a new CouponPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponPaymentWithDefaults() *CouponPayment {
	this := CouponPayment{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CouponPayment) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CouponPayment) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CouponPayment) SetId(v string) {
	o.Id = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *CouponPayment) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *CouponPayment) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *CouponPayment) SetAssetId(v string) {
	o.AssetId = &v
}

// GetYield returns the Yield field value if set, zero value otherwise.
func (o *CouponPayment) GetYield() float32 {
	if o == nil || IsNil(o.Yield) {
		var ret float32
		return ret
	}
	return *o.Yield
}

// GetYieldOk returns a tuple with the Yield field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetYieldOk() (*float32, bool) {
	if o == nil || IsNil(o.Yield) {
		return nil, false
	}
	return o.Yield, true
}

// HasYield returns a boolean if a field has been set.
func (o *CouponPayment) HasYield() bool {
	if o != nil && !IsNil(o.Yield) {
		return true
	}

	return false
}

// SetYield gets a reference to the given float32 and assigns it to the Yield field.
func (o *CouponPayment) SetYield(v float32) {
	o.Yield = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *CouponPayment) GetStartAt() time.Time {
	if o == nil || IsNil(o.StartAt) {
		var ret time.Time
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetStartAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *CouponPayment) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given time.Time and assigns it to the StartAt field.
func (o *CouponPayment) SetStartAt(v time.Time) {
	o.StartAt = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *CouponPayment) GetEndAt() time.Time {
	if o == nil || IsNil(o.EndAt) {
		var ret time.Time
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetEndAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *CouponPayment) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given time.Time and assigns it to the EndAt field.
func (o *CouponPayment) SetEndAt(v time.Time) {
	o.EndAt = &v
}

// GetPayAt returns the PayAt field value if set, zero value otherwise.
func (o *CouponPayment) GetPayAt() time.Time {
	if o == nil || IsNil(o.PayAt) {
		var ret time.Time
		return ret
	}
	return *o.PayAt
}

// GetPayAtOk returns a tuple with the PayAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetPayAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PayAt) {
		return nil, false
	}
	return o.PayAt, true
}

// HasPayAt returns a boolean if a field has been set.
func (o *CouponPayment) HasPayAt() bool {
	if o != nil && !IsNil(o.PayAt) {
		return true
	}

	return false
}

// SetPayAt gets a reference to the given time.Time and assigns it to the PayAt field.
func (o *CouponPayment) SetPayAt(v time.Time) {
	o.PayAt = &v
}

// GetAvailableToPay returns the AvailableToPay field value if set, zero value otherwise.
func (o *CouponPayment) GetAvailableToPay() float64 {
	if o == nil || IsNil(o.AvailableToPay) {
		var ret float64
		return ret
	}
	return *o.AvailableToPay
}

// GetAvailableToPayOk returns a tuple with the AvailableToPay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetAvailableToPayOk() (*float64, bool) {
	if o == nil || IsNil(o.AvailableToPay) {
		return nil, false
	}
	return o.AvailableToPay, true
}

// HasAvailableToPay returns a boolean if a field has been set.
func (o *CouponPayment) HasAvailableToPay() bool {
	if o != nil && !IsNil(o.AvailableToPay) {
		return true
	}

	return false
}

// SetAvailableToPay gets a reference to the given float64 and assigns it to the AvailableToPay field.
func (o *CouponPayment) SetAvailableToPay(v float64) {
	o.AvailableToPay = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *CouponPayment) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *CouponPayment) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given time.Time and assigns it to the CompletedAt field.
func (o *CouponPayment) SetCompletedAt(v time.Time) {
	o.CompletedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CouponPayment) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CouponPayment) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CouponPayment) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetProcessEvery returns the ProcessEvery field value if set, zero value otherwise.
func (o *CouponPayment) GetProcessEvery() int32 {
	if o == nil || IsNil(o.ProcessEvery) {
		var ret int32
		return ret
	}
	return *o.ProcessEvery
}

// GetProcessEveryOk returns a tuple with the ProcessEvery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetProcessEveryOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessEvery) {
		return nil, false
	}
	return o.ProcessEvery, true
}

// HasProcessEvery returns a boolean if a field has been set.
func (o *CouponPayment) HasProcessEvery() bool {
	if o != nil && !IsNil(o.ProcessEvery) {
		return true
	}

	return false
}

// SetProcessEvery gets a reference to the given int32 and assigns it to the ProcessEvery field.
func (o *CouponPayment) SetProcessEvery(v int32) {
	o.ProcessEvery = &v
}

// GetLastProcessedAt returns the LastProcessedAt field value if set, zero value otherwise.
func (o *CouponPayment) GetLastProcessedAt() time.Time {
	if o == nil || IsNil(o.LastProcessedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastProcessedAt
}

// GetLastProcessedAtOk returns a tuple with the LastProcessedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponPayment) GetLastProcessedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastProcessedAt) {
		return nil, false
	}
	return o.LastProcessedAt, true
}

// HasLastProcessedAt returns a boolean if a field has been set.
func (o *CouponPayment) HasLastProcessedAt() bool {
	if o != nil && !IsNil(o.LastProcessedAt) {
		return true
	}

	return false
}

// SetLastProcessedAt gets a reference to the given time.Time and assigns it to the LastProcessedAt field.
func (o *CouponPayment) SetLastProcessedAt(v time.Time) {
	o.LastProcessedAt = &v
}

func (o CouponPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CouponPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	if !IsNil(o.Yield) {
		toSerialize["yield"] = o.Yield
	}
	if !IsNil(o.StartAt) {
		toSerialize["start_at"] = o.StartAt
	}
	if !IsNil(o.EndAt) {
		toSerialize["end_at"] = o.EndAt
	}
	if !IsNil(o.PayAt) {
		toSerialize["pay_at"] = o.PayAt
	}
	if !IsNil(o.AvailableToPay) {
		toSerialize["available_to_pay"] = o.AvailableToPay
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.ProcessEvery) {
		toSerialize["process_every"] = o.ProcessEvery
	}
	if !IsNil(o.LastProcessedAt) {
		toSerialize["last_processed_at"] = o.LastProcessedAt
	}
	return toSerialize, nil
}

type NullableCouponPayment struct {
	value *CouponPayment
	isSet bool
}

func (v NullableCouponPayment) Get() *CouponPayment {
	return v.value
}

func (v *NullableCouponPayment) Set(val *CouponPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCouponPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCouponPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCouponPayment(val *CouponPayment) *NullableCouponPayment {
	return &NullableCouponPayment{value: val, isSet: true}
}

func (v NullableCouponPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCouponPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


