/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the WithdrawResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithdrawResponseEnvelope{}

// WithdrawResponseEnvelope struct for WithdrawResponseEnvelope
type WithdrawResponseEnvelope struct {
	Data interface{} `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	Metadata *Metadata `json:"metadata,omitempty"`
}

// NewWithdrawResponseEnvelope instantiates a new WithdrawResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawResponseEnvelope() *WithdrawResponseEnvelope {
	this := WithdrawResponseEnvelope{}
	return &this
}

// NewWithdrawResponseEnvelopeWithDefaults instantiates a new WithdrawResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawResponseEnvelopeWithDefaults() *WithdrawResponseEnvelope {
	this := WithdrawResponseEnvelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WithdrawResponseEnvelope) GetData() interface{} {
	if o == nil || IsNil(o.Data) {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawResponseEnvelope) GetDataOk() (interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WithdrawResponseEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *WithdrawResponseEnvelope) SetData(v interface{}) {
	o.Data = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WithdrawResponseEnvelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawResponseEnvelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WithdrawResponseEnvelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *WithdrawResponseEnvelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *WithdrawResponseEnvelope) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawResponseEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *WithdrawResponseEnvelope) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *WithdrawResponseEnvelope) SetMetadata(v Metadata) {
	o.Metadata = &v
}

func (o WithdrawResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithdrawResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableWithdrawResponseEnvelope struct {
	value *WithdrawResponseEnvelope
	isSet bool
}

func (v NullableWithdrawResponseEnvelope) Get() *WithdrawResponseEnvelope {
	return v.value
}

func (v *NullableWithdrawResponseEnvelope) Set(val *WithdrawResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawResponseEnvelope(val *WithdrawResponseEnvelope) *NullableWithdrawResponseEnvelope {
	return &NullableWithdrawResponseEnvelope{value: val, isSet: true}
}

func (v NullableWithdrawResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


