/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequest{}

// CreateOrderRequest struct for CreateOrderRequest
type CreateOrderRequest struct {
	Quantity float64 `json:"quantity"`
	InverseLeverage float64 `json:"inverse_leverage"`
	Price *float64 `json:"price,omitempty"`
	Kind OrderKind `json:"kind"`
	Side Side `json:"side"`
	// position ID to use for the order. required.
	PositionId string `json:"position_id"`
	// Required: the order book to submit the order to
	OrderBookId string `json:"order_book_id"`
	OrderModifiers []OrderModifierKind `json:"order_modifiers,omitempty"`
	GoodTillDate *time.Time `json:"good_till_date,omitempty"`
	TriggerPrice *float64 `json:"trigger_price,omitempty"`
}

type _CreateOrderRequest CreateOrderRequest

// NewCreateOrderRequest instantiates a new CreateOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequest(quantity float64, inverseLeverage float64, kind OrderKind, side Side, positionId string, orderBookId string) *CreateOrderRequest {
	this := CreateOrderRequest{}
	this.Quantity = quantity
	this.InverseLeverage = inverseLeverage
	this.Kind = kind
	this.Side = side
	this.PositionId = positionId
	this.OrderBookId = orderBookId
	return &this
}

// NewCreateOrderRequestWithDefaults instantiates a new CreateOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestWithDefaults() *CreateOrderRequest {
	this := CreateOrderRequest{}
	return &this
}

// GetQuantity returns the Quantity field value
func (o *CreateOrderRequest) GetQuantity() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetQuantityOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *CreateOrderRequest) SetQuantity(v float64) {
	o.Quantity = v
}

// GetInverseLeverage returns the InverseLeverage field value
func (o *CreateOrderRequest) GetInverseLeverage() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.InverseLeverage
}

// GetInverseLeverageOk returns a tuple with the InverseLeverage field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetInverseLeverageOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InverseLeverage, true
}

// SetInverseLeverage sets field value
func (o *CreateOrderRequest) SetInverseLeverage(v float64) {
	o.InverseLeverage = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *CreateOrderRequest) GetPrice() float64 {
	if o == nil || IsNil(o.Price) {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *CreateOrderRequest) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *CreateOrderRequest) SetPrice(v float64) {
	o.Price = &v
}

// GetKind returns the Kind field value
func (o *CreateOrderRequest) GetKind() OrderKind {
	if o == nil {
		var ret OrderKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetKindOk() (*OrderKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CreateOrderRequest) SetKind(v OrderKind) {
	o.Kind = v
}

// GetSide returns the Side field value
func (o *CreateOrderRequest) GetSide() Side {
	if o == nil {
		var ret Side
		return ret
	}

	return o.Side
}

// GetSideOk returns a tuple with the Side field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetSideOk() (*Side, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Side, true
}

// SetSide sets field value
func (o *CreateOrderRequest) SetSide(v Side) {
	o.Side = v
}

// GetPositionId returns the PositionId field value
func (o *CreateOrderRequest) GetPositionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetPositionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionId, true
}

// SetPositionId sets field value
func (o *CreateOrderRequest) SetPositionId(v string) {
	o.PositionId = v
}

// GetOrderBookId returns the OrderBookId field value
func (o *CreateOrderRequest) GetOrderBookId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderBookId
}

// GetOrderBookIdOk returns a tuple with the OrderBookId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetOrderBookIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderBookId, true
}

// SetOrderBookId sets field value
func (o *CreateOrderRequest) SetOrderBookId(v string) {
	o.OrderBookId = v
}

// GetOrderModifiers returns the OrderModifiers field value if set, zero value otherwise.
func (o *CreateOrderRequest) GetOrderModifiers() []OrderModifierKind {
	if o == nil || IsNil(o.OrderModifiers) {
		var ret []OrderModifierKind
		return ret
	}
	return o.OrderModifiers
}

// GetOrderModifiersOk returns a tuple with the OrderModifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetOrderModifiersOk() ([]OrderModifierKind, bool) {
	if o == nil || IsNil(o.OrderModifiers) {
		return nil, false
	}
	return o.OrderModifiers, true
}

// HasOrderModifiers returns a boolean if a field has been set.
func (o *CreateOrderRequest) HasOrderModifiers() bool {
	if o != nil && !IsNil(o.OrderModifiers) {
		return true
	}

	return false
}

// SetOrderModifiers gets a reference to the given []OrderModifierKind and assigns it to the OrderModifiers field.
func (o *CreateOrderRequest) SetOrderModifiers(v []OrderModifierKind) {
	o.OrderModifiers = v
}

// GetGoodTillDate returns the GoodTillDate field value if set, zero value otherwise.
func (o *CreateOrderRequest) GetGoodTillDate() time.Time {
	if o == nil || IsNil(o.GoodTillDate) {
		var ret time.Time
		return ret
	}
	return *o.GoodTillDate
}

// GetGoodTillDateOk returns a tuple with the GoodTillDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetGoodTillDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.GoodTillDate) {
		return nil, false
	}
	return o.GoodTillDate, true
}

// HasGoodTillDate returns a boolean if a field has been set.
func (o *CreateOrderRequest) HasGoodTillDate() bool {
	if o != nil && !IsNil(o.GoodTillDate) {
		return true
	}

	return false
}

// SetGoodTillDate gets a reference to the given time.Time and assigns it to the GoodTillDate field.
func (o *CreateOrderRequest) SetGoodTillDate(v time.Time) {
	o.GoodTillDate = &v
}

// GetTriggerPrice returns the TriggerPrice field value if set, zero value otherwise.
func (o *CreateOrderRequest) GetTriggerPrice() float64 {
	if o == nil || IsNil(o.TriggerPrice) {
		var ret float64
		return ret
	}
	return *o.TriggerPrice
}

// GetTriggerPriceOk returns a tuple with the TriggerPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetTriggerPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.TriggerPrice) {
		return nil, false
	}
	return o.TriggerPrice, true
}

// HasTriggerPrice returns a boolean if a field has been set.
func (o *CreateOrderRequest) HasTriggerPrice() bool {
	if o != nil && !IsNil(o.TriggerPrice) {
		return true
	}

	return false
}

// SetTriggerPrice gets a reference to the given float64 and assigns it to the TriggerPrice field.
func (o *CreateOrderRequest) SetTriggerPrice(v float64) {
	o.TriggerPrice = &v
}

func (o CreateOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quantity"] = o.Quantity
	toSerialize["inverse_leverage"] = o.InverseLeverage
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	toSerialize["kind"] = o.Kind
	toSerialize["side"] = o.Side
	toSerialize["position_id"] = o.PositionId
	toSerialize["order_book_id"] = o.OrderBookId
	if !IsNil(o.OrderModifiers) {
		toSerialize["order_modifiers"] = o.OrderModifiers
	}
	if !IsNil(o.GoodTillDate) {
		toSerialize["good_till_date"] = o.GoodTillDate
	}
	if !IsNil(o.TriggerPrice) {
		toSerialize["trigger_price"] = o.TriggerPrice
	}
	return toSerialize, nil
}

func (o *CreateOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quantity",
		"inverse_leverage",
		"kind",
		"side",
		"position_id",
		"order_book_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderRequest := _CreateOrderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderRequest)

	if err != nil {
		return err
	}

	*o = CreateOrderRequest(varCreateOrderRequest)

	return err
}

type NullableCreateOrderRequest struct {
	value *CreateOrderRequest
	isSet bool
}

func (v NullableCreateOrderRequest) Get() *CreateOrderRequest {
	return v.value
}

func (v *NullableCreateOrderRequest) Set(val *CreateOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequest(val *CreateOrderRequest) *NullableCreateOrderRequest {
	return &NullableCreateOrderRequest{value: val, isSet: true}
}

func (v NullableCreateOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


