/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the RevokeAPIKeyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeAPIKeyData{}

// RevokeAPIKeyData struct for RevokeAPIKeyData
type RevokeAPIKeyData struct {
	UserId *string `json:"user_id,omitempty"`
	KeyId *string `json:"key_id,omitempty"`
	Label *string `json:"label,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
}

// NewRevokeAPIKeyData instantiates a new RevokeAPIKeyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeAPIKeyData() *RevokeAPIKeyData {
	this := RevokeAPIKeyData{}
	return &this
}

// NewRevokeAPIKeyDataWithDefaults instantiates a new RevokeAPIKeyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeAPIKeyDataWithDefaults() *RevokeAPIKeyData {
	this := RevokeAPIKeyData{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *RevokeAPIKeyData) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeAPIKeyData) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *RevokeAPIKeyData) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *RevokeAPIKeyData) SetUserId(v string) {
	o.UserId = &v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *RevokeAPIKeyData) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeAPIKeyData) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *RevokeAPIKeyData) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *RevokeAPIKeyData) SetKeyId(v string) {
	o.KeyId = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *RevokeAPIKeyData) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeAPIKeyData) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *RevokeAPIKeyData) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *RevokeAPIKeyData) SetLabel(v string) {
	o.Label = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *RevokeAPIKeyData) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeAPIKeyData) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *RevokeAPIKeyData) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *RevokeAPIKeyData) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o RevokeAPIKeyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeAPIKeyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.KeyId) {
		toSerialize["key_id"] = o.KeyId
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	return toSerialize, nil
}

type NullableRevokeAPIKeyData struct {
	value *RevokeAPIKeyData
	isSet bool
}

func (v NullableRevokeAPIKeyData) Get() *RevokeAPIKeyData {
	return v.value
}

func (v *NullableRevokeAPIKeyData) Set(val *RevokeAPIKeyData) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeAPIKeyData) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeAPIKeyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeAPIKeyData(val *RevokeAPIKeyData) *NullableRevokeAPIKeyData {
	return &NullableRevokeAPIKeyData{value: val, isSet: true}
}

func (v NullableRevokeAPIKeyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeAPIKeyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


