/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient
import (
	"time"
)

type Trade struct {
	TransactionId string `json:"transaction_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	OrderSeq int32 `json:"order_seq,omitempty"`
	OrderBookId string `json:"order_book_id,omitempty"`
	AssetId string `json:"asset_id,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	Price string `json:"price,omitempty"`
	FeeAssetId string `json:"fee_asset_id,omitempty"`
	FeeQuantity string `json:"fee_quantity,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
}
