/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the PayLeverageAccruedInterest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayLeverageAccruedInterest{}

// PayLeverageAccruedInterest struct for PayLeverageAccruedInterest
type PayLeverageAccruedInterest struct {
	TransactionId *string `json:"transaction_id,omitempty"`
	AssetId *string `json:"asset_id,omitempty"`
	PositionId *string `json:"position_id,omitempty"`
	CurrentAccruedInterest *string `json:"current_accrued_interest,omitempty"`
}

// NewPayLeverageAccruedInterest instantiates a new PayLeverageAccruedInterest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayLeverageAccruedInterest() *PayLeverageAccruedInterest {
	this := PayLeverageAccruedInterest{}
	return &this
}

// NewPayLeverageAccruedInterestWithDefaults instantiates a new PayLeverageAccruedInterest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayLeverageAccruedInterestWithDefaults() *PayLeverageAccruedInterest {
	this := PayLeverageAccruedInterest{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *PayLeverageAccruedInterest) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayLeverageAccruedInterest) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *PayLeverageAccruedInterest) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *PayLeverageAccruedInterest) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *PayLeverageAccruedInterest) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayLeverageAccruedInterest) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *PayLeverageAccruedInterest) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *PayLeverageAccruedInterest) SetAssetId(v string) {
	o.AssetId = &v
}

// GetPositionId returns the PositionId field value if set, zero value otherwise.
func (o *PayLeverageAccruedInterest) GetPositionId() string {
	if o == nil || IsNil(o.PositionId) {
		var ret string
		return ret
	}
	return *o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayLeverageAccruedInterest) GetPositionIdOk() (*string, bool) {
	if o == nil || IsNil(o.PositionId) {
		return nil, false
	}
	return o.PositionId, true
}

// HasPositionId returns a boolean if a field has been set.
func (o *PayLeverageAccruedInterest) HasPositionId() bool {
	if o != nil && !IsNil(o.PositionId) {
		return true
	}

	return false
}

// SetPositionId gets a reference to the given string and assigns it to the PositionId field.
func (o *PayLeverageAccruedInterest) SetPositionId(v string) {
	o.PositionId = &v
}

// GetCurrentAccruedInterest returns the CurrentAccruedInterest field value if set, zero value otherwise.
func (o *PayLeverageAccruedInterest) GetCurrentAccruedInterest() string {
	if o == nil || IsNil(o.CurrentAccruedInterest) {
		var ret string
		return ret
	}
	return *o.CurrentAccruedInterest
}

// GetCurrentAccruedInterestOk returns a tuple with the CurrentAccruedInterest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayLeverageAccruedInterest) GetCurrentAccruedInterestOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentAccruedInterest) {
		return nil, false
	}
	return o.CurrentAccruedInterest, true
}

// HasCurrentAccruedInterest returns a boolean if a field has been set.
func (o *PayLeverageAccruedInterest) HasCurrentAccruedInterest() bool {
	if o != nil && !IsNil(o.CurrentAccruedInterest) {
		return true
	}

	return false
}

// SetCurrentAccruedInterest gets a reference to the given string and assigns it to the CurrentAccruedInterest field.
func (o *PayLeverageAccruedInterest) SetCurrentAccruedInterest(v string) {
	o.CurrentAccruedInterest = &v
}

func (o PayLeverageAccruedInterest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayLeverageAccruedInterest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	if !IsNil(o.PositionId) {
		toSerialize["position_id"] = o.PositionId
	}
	if !IsNil(o.CurrentAccruedInterest) {
		toSerialize["current_accrued_interest"] = o.CurrentAccruedInterest
	}
	return toSerialize, nil
}

type NullablePayLeverageAccruedInterest struct {
	value *PayLeverageAccruedInterest
	isSet bool
}

func (v NullablePayLeverageAccruedInterest) Get() *PayLeverageAccruedInterest {
	return v.value
}

func (v *NullablePayLeverageAccruedInterest) Set(val *PayLeverageAccruedInterest) {
	v.value = val
	v.isSet = true
}

func (v NullablePayLeverageAccruedInterest) IsSet() bool {
	return v.isSet
}

func (v *NullablePayLeverageAccruedInterest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayLeverageAccruedInterest(val *PayLeverageAccruedInterest) *NullablePayLeverageAccruedInterest {
	return &NullablePayLeverageAccruedInterest{value: val, isSet: true}
}

func (v NullablePayLeverageAccruedInterest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayLeverageAccruedInterest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


