/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type BondKind string

// List of BondKind
const (
	COUPON_PAYING_BondKind BondKind = "COUPON-PAYING"
	PRINCIPAL_ONLY_BondKind BondKind = "PRINCIPAL-ONLY"
)
