/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the StreamCandlesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamCandlesResponse{}

// StreamCandlesResponse struct for StreamCandlesResponse
type StreamCandlesResponse struct {
}

// NewStreamCandlesResponse instantiates a new StreamCandlesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamCandlesResponse() *StreamCandlesResponse {
	this := StreamCandlesResponse{}
	return &this
}

// NewStreamCandlesResponseWithDefaults instantiates a new StreamCandlesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamCandlesResponseWithDefaults() *StreamCandlesResponse {
	this := StreamCandlesResponse{}
	return &this
}

func (o StreamCandlesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamCandlesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := make([]interface{}, len(o.Items))
	for i, item := range o.Items {
		toSerialize[i] = item
	}
	return toSerialize, nil
}

func (o *StreamCandlesResponse) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &o.Items)
}

type NullableStreamCandlesResponse struct {
	value StreamCandlesResponse
	isSet bool
}

func (v NullableStreamCandlesResponse) Get() StreamCandlesResponse {
	return v.value
}

func (v *NullableStreamCandlesResponse) Set(val StreamCandlesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamCandlesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamCandlesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamCandlesResponse(val StreamCandlesResponse) *NullableStreamCandlesResponse {
	return &NullableStreamCandlesResponse{value: val, isSet: true}
}

func (v NullableStreamCandlesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamCandlesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


