/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CopyTrader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CopyTrader{}

// CopyTrader struct for CopyTrader
type CopyTrader struct {
	UserId string `json:"user_id"`
	UserName string `json:"user_name"`
}

type _CopyTrader CopyTrader

// NewCopyTrader instantiates a new CopyTrader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCopyTrader(userId string, userName string) *CopyTrader {
	this := CopyTrader{}
	this.UserId = userId
	this.UserName = userName
	return &this
}

// NewCopyTraderWithDefaults instantiates a new CopyTrader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCopyTraderWithDefaults() *CopyTrader {
	this := CopyTrader{}
	return &this
}

// GetUserId returns the UserId field value
func (o *CopyTrader) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CopyTrader) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CopyTrader) SetUserId(v string) {
	o.UserId = v
}

// GetUserName returns the UserName field value
func (o *CopyTrader) GetUserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
func (o *CopyTrader) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserName, true
}

// SetUserName sets field value
func (o *CopyTrader) SetUserName(v string) {
	o.UserName = v
}

func (o CopyTrader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CopyTrader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["user_name"] = o.UserName
	return toSerialize, nil
}

func (o *CopyTrader) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"user_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCopyTrader := _CopyTrader{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCopyTrader)

	if err != nil {
		return err
	}

	*o = CopyTrader(varCopyTrader)

	return err
}

type NullableCopyTrader struct {
	value *CopyTrader
	isSet bool
}

func (v NullableCopyTrader) Get() *CopyTrader {
	return v.value
}

func (v *NullableCopyTrader) Set(val *CopyTrader) {
	v.value = val
	v.isSet = true
}

func (v NullableCopyTrader) IsSet() bool {
	return v.isSet
}

func (v *NullableCopyTrader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCopyTrader(val *CopyTrader) *NullableCopyTrader {
	return &NullableCopyTrader{value: val, isSet: true}
}

func (v NullableCopyTrader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCopyTrader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


