/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IsolateCollateralResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsolateCollateralResponse{}

// IsolateCollateralResponse struct for IsolateCollateralResponse
type IsolateCollateralResponse struct {
	Data *IsolatedCollateral `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	// Metadata about the response, including status code and trace information.
	Metadata Metadata `json:"metadata"`
}

type _IsolateCollateralResponse IsolateCollateralResponse

// NewIsolateCollateralResponse instantiates a new IsolateCollateralResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsolateCollateralResponse(metadata Metadata) *IsolateCollateralResponse {
	this := IsolateCollateralResponse{}
	this.Metadata = metadata
	return &this
}

// NewIsolateCollateralResponseWithDefaults instantiates a new IsolateCollateralResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsolateCollateralResponseWithDefaults() *IsolateCollateralResponse {
	this := IsolateCollateralResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IsolateCollateralResponse) GetData() IsolatedCollateral {
	if o == nil || IsNil(o.Data) {
		var ret IsolatedCollateral
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolateCollateralResponse) GetDataOk() (*IsolatedCollateral, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IsolateCollateralResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given IsolatedCollateral and assigns it to the Data field.
func (o *IsolateCollateralResponse) SetData(v IsolatedCollateral) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *IsolateCollateralResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolateCollateralResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *IsolateCollateralResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *IsolateCollateralResponse) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value
func (o *IsolateCollateralResponse) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *IsolateCollateralResponse) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *IsolateCollateralResponse) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o IsolateCollateralResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsolateCollateralResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *IsolateCollateralResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIsolateCollateralResponse := _IsolateCollateralResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIsolateCollateralResponse)

	if err != nil {
		return err
	}

	*o = IsolateCollateralResponse(varIsolateCollateralResponse)

	return err
}

type NullableIsolateCollateralResponse struct {
	value *IsolateCollateralResponse
	isSet bool
}

func (v NullableIsolateCollateralResponse) Get() *IsolateCollateralResponse {
	return v.value
}

func (v *NullableIsolateCollateralResponse) Set(val *IsolateCollateralResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIsolateCollateralResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIsolateCollateralResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsolateCollateralResponse(val *IsolateCollateralResponse) *NullableIsolateCollateralResponse {
	return &NullableIsolateCollateralResponse{value: val, isSet: true}
}

func (v NullableIsolateCollateralResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsolateCollateralResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


