/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the PLSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PLSummary{}

// PLSummary struct for PLSummary
type PLSummary struct {
	// The leverage used to obtain the position on the isolated account
	Leverage *float64 `json:"leverage,omitempty"`
	AccountEquity *float64 `json:"account_equity,omitempty"`
	Available *float64 `json:"available,omitempty"`
	Health *float64 `json:"health,omitempty"`
}

// NewPLSummary instantiates a new PLSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPLSummary() *PLSummary {
	this := PLSummary{}
	return &this
}

// NewPLSummaryWithDefaults instantiates a new PLSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPLSummaryWithDefaults() *PLSummary {
	this := PLSummary{}
	return &this
}

// GetLeverage returns the Leverage field value if set, zero value otherwise.
func (o *PLSummary) GetLeverage() float64 {
	if o == nil || IsNil(o.Leverage) {
		var ret float64
		return ret
	}
	return *o.Leverage
}

// GetLeverageOk returns a tuple with the Leverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLSummary) GetLeverageOk() (*float64, bool) {
	if o == nil || IsNil(o.Leverage) {
		return nil, false
	}
	return o.Leverage, true
}

// HasLeverage returns a boolean if a field has been set.
func (o *PLSummary) HasLeverage() bool {
	if o != nil && !IsNil(o.Leverage) {
		return true
	}

	return false
}

// SetLeverage gets a reference to the given float64 and assigns it to the Leverage field.
func (o *PLSummary) SetLeverage(v float64) {
	o.Leverage = &v
}

// GetAccountEquity returns the AccountEquity field value if set, zero value otherwise.
func (o *PLSummary) GetAccountEquity() float64 {
	if o == nil || IsNil(o.AccountEquity) {
		var ret float64
		return ret
	}
	return *o.AccountEquity
}

// GetAccountEquityOk returns a tuple with the AccountEquity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLSummary) GetAccountEquityOk() (*float64, bool) {
	if o == nil || IsNil(o.AccountEquity) {
		return nil, false
	}
	return o.AccountEquity, true
}

// HasAccountEquity returns a boolean if a field has been set.
func (o *PLSummary) HasAccountEquity() bool {
	if o != nil && !IsNil(o.AccountEquity) {
		return true
	}

	return false
}

// SetAccountEquity gets a reference to the given float64 and assigns it to the AccountEquity field.
func (o *PLSummary) SetAccountEquity(v float64) {
	o.AccountEquity = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *PLSummary) GetAvailable() float64 {
	if o == nil || IsNil(o.Available) {
		var ret float64
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLSummary) GetAvailableOk() (*float64, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *PLSummary) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given float64 and assigns it to the Available field.
func (o *PLSummary) SetAvailable(v float64) {
	o.Available = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *PLSummary) GetHealth() float64 {
	if o == nil || IsNil(o.Health) {
		var ret float64
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLSummary) GetHealthOk() (*float64, bool) {
	if o == nil || IsNil(o.Health) {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *PLSummary) HasHealth() bool {
	if o != nil && !IsNil(o.Health) {
		return true
	}

	return false
}

// SetHealth gets a reference to the given float64 and assigns it to the Health field.
func (o *PLSummary) SetHealth(v float64) {
	o.Health = &v
}

func (o PLSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PLSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Leverage) {
		toSerialize["leverage"] = o.Leverage
	}
	if !IsNil(o.AccountEquity) {
		toSerialize["account_equity"] = o.AccountEquity
	}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Health) {
		toSerialize["health"] = o.Health
	}
	return toSerialize, nil
}

type NullablePLSummary struct {
	value *PLSummary
	isSet bool
}

func (v NullablePLSummary) Get() *PLSummary {
	return v.value
}

func (v *NullablePLSummary) Set(val *PLSummary) {
	v.value = val
	v.isSet = true
}

func (v NullablePLSummary) IsSet() bool {
	return v.isSet
}

func (v *NullablePLSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePLSummary(val *PLSummary) *NullablePLSummary {
	return &NullablePLSummary{value: val, isSet: true}
}

func (v NullablePLSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePLSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


