/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderBookSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderBookSummary{}

// OrderBookSummary struct for OrderBookSummary
type OrderBookSummary struct {
	OrderBookId string `json:"order_book_id"`
	MidPrice string `json:"mid_price"`
	Spread string `json:"spread"`
	BestBid string `json:"best_bid"`
	BestAsk string `json:"best_ask"`
}

type _OrderBookSummary OrderBookSummary

// NewOrderBookSummary instantiates a new OrderBookSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderBookSummary(orderBookId string, midPrice string, spread string, bestBid string, bestAsk string) *OrderBookSummary {
	this := OrderBookSummary{}
	this.OrderBookId = orderBookId
	this.MidPrice = midPrice
	this.Spread = spread
	this.BestBid = bestBid
	this.BestAsk = bestAsk
	return &this
}

// NewOrderBookSummaryWithDefaults instantiates a new OrderBookSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderBookSummaryWithDefaults() *OrderBookSummary {
	this := OrderBookSummary{}
	return &this
}

// GetOrderBookId returns the OrderBookId field value
func (o *OrderBookSummary) GetOrderBookId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderBookId
}

// GetOrderBookIdOk returns a tuple with the OrderBookId field value
// and a boolean to check if the value has been set.
func (o *OrderBookSummary) GetOrderBookIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderBookId, true
}

// SetOrderBookId sets field value
func (o *OrderBookSummary) SetOrderBookId(v string) {
	o.OrderBookId = v
}

// GetMidPrice returns the MidPrice field value
func (o *OrderBookSummary) GetMidPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MidPrice
}

// GetMidPriceOk returns a tuple with the MidPrice field value
// and a boolean to check if the value has been set.
func (o *OrderBookSummary) GetMidPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MidPrice, true
}

// SetMidPrice sets field value
func (o *OrderBookSummary) SetMidPrice(v string) {
	o.MidPrice = v
}

// GetSpread returns the Spread field value
func (o *OrderBookSummary) GetSpread() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Spread
}

// GetSpreadOk returns a tuple with the Spread field value
// and a boolean to check if the value has been set.
func (o *OrderBookSummary) GetSpreadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spread, true
}

// SetSpread sets field value
func (o *OrderBookSummary) SetSpread(v string) {
	o.Spread = v
}

// GetBestBid returns the BestBid field value
func (o *OrderBookSummary) GetBestBid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BestBid
}

// GetBestBidOk returns a tuple with the BestBid field value
// and a boolean to check if the value has been set.
func (o *OrderBookSummary) GetBestBidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BestBid, true
}

// SetBestBid sets field value
func (o *OrderBookSummary) SetBestBid(v string) {
	o.BestBid = v
}

// GetBestAsk returns the BestAsk field value
func (o *OrderBookSummary) GetBestAsk() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BestAsk
}

// GetBestAskOk returns a tuple with the BestAsk field value
// and a boolean to check if the value has been set.
func (o *OrderBookSummary) GetBestAskOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BestAsk, true
}

// SetBestAsk sets field value
func (o *OrderBookSummary) SetBestAsk(v string) {
	o.BestAsk = v
}

func (o OrderBookSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderBookSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order_book_id"] = o.OrderBookId
	toSerialize["mid_price"] = o.MidPrice
	toSerialize["spread"] = o.Spread
	toSerialize["best_bid"] = o.BestBid
	toSerialize["best_ask"] = o.BestAsk
	return toSerialize, nil
}

func (o *OrderBookSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order_book_id",
		"mid_price",
		"spread",
		"best_bid",
		"best_ask",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderBookSummary := _OrderBookSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderBookSummary)

	if err != nil {
		return err
	}

	*o = OrderBookSummary(varOrderBookSummary)

	return err
}

type NullableOrderBookSummary struct {
	value *OrderBookSummary
	isSet bool
}

func (v NullableOrderBookSummary) Get() *OrderBookSummary {
	return v.value
}

func (v *NullableOrderBookSummary) Set(val *OrderBookSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderBookSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderBookSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderBookSummary(val *OrderBookSummary) *NullableOrderBookSummary {
	return &NullableOrderBookSummary{value: val, isSet: true}
}

func (v NullableOrderBookSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderBookSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


