/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type WithdrawRequest struct {
	PositionId string `json:"position_id,omitempty"`
	AssetId string `json:"asset_id,omitempty"`
	Quantity string `json:"quantity,omitempty"`
}
