/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the StreamCandlesEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamCandlesEntry{}

// StreamCandlesEntry struct for StreamCandlesEntry
type StreamCandlesEntry struct {
	Val Candle `json:"Val"`
	// The timestamp when the data was created
	Time time.Time `json:"Time"`
}

type _StreamCandlesEntry StreamCandlesEntry

// NewStreamCandlesEntry instantiates a new StreamCandlesEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamCandlesEntry(val Candle, time time.Time) *StreamCandlesEntry {
	this := StreamCandlesEntry{}
	this.Val = val
	this.Time = time
	return &this
}

// NewStreamCandlesEntryWithDefaults instantiates a new StreamCandlesEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamCandlesEntryWithDefaults() *StreamCandlesEntry {
	this := StreamCandlesEntry{}
	return &this
}

// GetVal returns the Val field value
func (o *StreamCandlesEntry) GetVal() Candle {
	if o == nil {
		var ret Candle
		return ret
	}

	return o.Val
}

// GetValOk returns a tuple with the Val field value
// and a boolean to check if the value has been set.
func (o *StreamCandlesEntry) GetValOk() (*Candle, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Val, true
}

// SetVal sets field value
func (o *StreamCandlesEntry) SetVal(v Candle) {
	o.Val = v
}

// GetTime returns the Time field value
func (o *StreamCandlesEntry) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *StreamCandlesEntry) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *StreamCandlesEntry) SetTime(v time.Time) {
	o.Time = v
}

func (o StreamCandlesEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamCandlesEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Val"] = o.Val
	toSerialize["Time"] = o.Time
	return toSerialize, nil
}

func (o *StreamCandlesEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Val",
		"Time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamCandlesEntry := _StreamCandlesEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamCandlesEntry)

	if err != nil {
		return err
	}

	*o = StreamCandlesEntry(varStreamCandlesEntry)

	return err
}

type NullableStreamCandlesEntry struct {
	value *StreamCandlesEntry
	isSet bool
}

func (v NullableStreamCandlesEntry) Get() *StreamCandlesEntry {
	return v.value
}

func (v *NullableStreamCandlesEntry) Set(val *StreamCandlesEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamCandlesEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamCandlesEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamCandlesEntry(val *StreamCandlesEntry) *NullableStreamCandlesEntry {
	return &NullableStreamCandlesEntry{value: val, isSet: true}
}

func (v NullableStreamCandlesEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamCandlesEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


