/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type IsolatePositionResponse struct {
	GlobalPositionId string `json:"global_position_id,omitempty"`
	IsolatedPositionId string `json:"isolated_position_id,omitempty"`
	TransactionId string `json:"transaction_id,omitempty"`
}
