/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DepositCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepositCall{}

// DepositCall Descriptor of the vault deposit() transaction the client builds after signing the permit. The client splits the permit signature into v/r/s and ABI-encodes function_signature with args plus (v, r, s) to produce the calldata sent to 'to'.
type DepositCall struct {
	// The vault contract address, as a 0x-prefixed hex string.
	To string `json:"to"`
	// EVM chain ID, as a JSON number.
	ChainId int64 `json:"chain_id"`
	// Native currency value to send with the transaction. Always '0'.
	Value string `json:"value"`
	// Canonical Solidity signature of the vault's permit-aware deposit function: deposit(uint256,bytes16,bytes32,uint256,uint8,bytes32,bytes32).
	FunctionSignature string `json:"function_signature"`
	// The 4-byte ABI call selector of function_signature, as a 0x-prefixed hex string.
	Selector string `json:"selector"`
	Args DepositArgs `json:"args"`
}

type _DepositCall DepositCall

// NewDepositCall instantiates a new DepositCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepositCall(to string, chainId int64, value string, functionSignature string, selector string, args DepositArgs) *DepositCall {
	this := DepositCall{}
	this.To = to
	this.ChainId = chainId
	this.Value = value
	this.FunctionSignature = functionSignature
	this.Selector = selector
	this.Args = args
	return &this
}

// NewDepositCallWithDefaults instantiates a new DepositCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepositCallWithDefaults() *DepositCall {
	this := DepositCall{}
	return &this
}

// GetTo returns the To field value
func (o *DepositCall) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *DepositCall) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *DepositCall) SetTo(v string) {
	o.To = v
}

// GetChainId returns the ChainId field value
func (o *DepositCall) GetChainId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *DepositCall) GetChainIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *DepositCall) SetChainId(v int64) {
	o.ChainId = v
}

// GetValue returns the Value field value
func (o *DepositCall) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *DepositCall) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *DepositCall) SetValue(v string) {
	o.Value = v
}

// GetFunctionSignature returns the FunctionSignature field value
func (o *DepositCall) GetFunctionSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FunctionSignature
}

// GetFunctionSignatureOk returns a tuple with the FunctionSignature field value
// and a boolean to check if the value has been set.
func (o *DepositCall) GetFunctionSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FunctionSignature, true
}

// SetFunctionSignature sets field value
func (o *DepositCall) SetFunctionSignature(v string) {
	o.FunctionSignature = v
}

// GetSelector returns the Selector field value
func (o *DepositCall) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *DepositCall) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *DepositCall) SetSelector(v string) {
	o.Selector = v
}

// GetArgs returns the Args field value
func (o *DepositCall) GetArgs() DepositArgs {
	if o == nil {
		var ret DepositArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *DepositCall) GetArgsOk() (*DepositArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *DepositCall) SetArgs(v DepositArgs) {
	o.Args = v
}

func (o DepositCall) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepositCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["to"] = o.To
	toSerialize["chain_id"] = o.ChainId
	toSerialize["value"] = o.Value
	toSerialize["function_signature"] = o.FunctionSignature
	toSerialize["selector"] = o.Selector
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *DepositCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"to",
		"chain_id",
		"value",
		"function_signature",
		"selector",
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDepositCall := _DepositCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDepositCall)

	if err != nil {
		return err
	}

	*o = DepositCall(varDepositCall)

	return err
}

type NullableDepositCall struct {
	value *DepositCall
	isSet bool
}

func (v NullableDepositCall) Get() *DepositCall {
	return v.value
}

func (v *NullableDepositCall) Set(val *DepositCall) {
	v.value = val
	v.isSet = true
}

func (v NullableDepositCall) IsSet() bool {
	return v.isSet
}

func (v *NullableDepositCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepositCall(val *DepositCall) *NullableDepositCall {
	return &NullableDepositCall{value: val, isSet: true}
}

func (v NullableDepositCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepositCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


