/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserValue{}

// UserValue struct for UserValue
type UserValue struct {
	Available map[string]string `json:"available"`
	Locked map[string]string `json:"locked"`
	Borrowed map[string]string `json:"borrowed"`
	Supplied map[string]string `json:"supplied"`
	ImpendingBorrows map[string]string `json:"impending_borrows"`
	BorrowLimit map[string]string `json:"borrow_limit"`
	LiquidationThreshold map[string]string `json:"liquidation_threshold"`
}

type _UserValue UserValue

// NewUserValue instantiates a new UserValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserValue(available map[string]string, locked map[string]string, borrowed map[string]string, supplied map[string]string, impendingBorrows map[string]string, borrowLimit map[string]string, liquidationThreshold map[string]string) *UserValue {
	this := UserValue{}
	this.Available = available
	this.Locked = locked
	this.Borrowed = borrowed
	this.Supplied = supplied
	this.ImpendingBorrows = impendingBorrows
	this.BorrowLimit = borrowLimit
	this.LiquidationThreshold = liquidationThreshold
	return &this
}

// NewUserValueWithDefaults instantiates a new UserValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserValueWithDefaults() *UserValue {
	this := UserValue{}
	return &this
}

// GetAvailable returns the Available field value
func (o *UserValue) GetAvailable() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetAvailableOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Available, true
}

// SetAvailable sets field value
func (o *UserValue) SetAvailable(v map[string]string) {
	o.Available = v
}

// GetLocked returns the Locked field value
func (o *UserValue) GetLocked() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Locked
}

// GetLockedOk returns a tuple with the Locked field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetLockedOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Locked, true
}

// SetLocked sets field value
func (o *UserValue) SetLocked(v map[string]string) {
	o.Locked = v
}

// GetBorrowed returns the Borrowed field value
func (o *UserValue) GetBorrowed() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Borrowed
}

// GetBorrowedOk returns a tuple with the Borrowed field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetBorrowedOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Borrowed, true
}

// SetBorrowed sets field value
func (o *UserValue) SetBorrowed(v map[string]string) {
	o.Borrowed = v
}

// GetSupplied returns the Supplied field value
func (o *UserValue) GetSupplied() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Supplied
}

// GetSuppliedOk returns a tuple with the Supplied field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetSuppliedOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Supplied, true
}

// SetSupplied sets field value
func (o *UserValue) SetSupplied(v map[string]string) {
	o.Supplied = v
}

// GetImpendingBorrows returns the ImpendingBorrows field value
func (o *UserValue) GetImpendingBorrows() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.ImpendingBorrows
}

// GetImpendingBorrowsOk returns a tuple with the ImpendingBorrows field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetImpendingBorrowsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.ImpendingBorrows, true
}

// SetImpendingBorrows sets field value
func (o *UserValue) SetImpendingBorrows(v map[string]string) {
	o.ImpendingBorrows = v
}

// GetBorrowLimit returns the BorrowLimit field value
func (o *UserValue) GetBorrowLimit() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.BorrowLimit
}

// GetBorrowLimitOk returns a tuple with the BorrowLimit field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetBorrowLimitOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.BorrowLimit, true
}

// SetBorrowLimit sets field value
func (o *UserValue) SetBorrowLimit(v map[string]string) {
	o.BorrowLimit = v
}

// GetLiquidationThreshold returns the LiquidationThreshold field value
func (o *UserValue) GetLiquidationThreshold() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.LiquidationThreshold
}

// GetLiquidationThresholdOk returns a tuple with the LiquidationThreshold field value
// and a boolean to check if the value has been set.
func (o *UserValue) GetLiquidationThresholdOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.LiquidationThreshold, true
}

// SetLiquidationThreshold sets field value
func (o *UserValue) SetLiquidationThreshold(v map[string]string) {
	o.LiquidationThreshold = v
}

func (o UserValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["available"] = o.Available
	toSerialize["locked"] = o.Locked
	toSerialize["borrowed"] = o.Borrowed
	toSerialize["supplied"] = o.Supplied
	toSerialize["impending_borrows"] = o.ImpendingBorrows
	toSerialize["borrow_limit"] = o.BorrowLimit
	toSerialize["liquidation_threshold"] = o.LiquidationThreshold
	return toSerialize, nil
}

func (o *UserValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"available",
		"locked",
		"borrowed",
		"supplied",
		"impending_borrows",
		"borrow_limit",
		"liquidation_threshold",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserValue := _UserValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserValue)

	if err != nil {
		return err
	}

	*o = UserValue(varUserValue)

	return err
}

type NullableUserValue struct {
	value *UserValue
	isSet bool
}

func (v NullableUserValue) Get() *UserValue {
	return v.value
}

func (v *NullableUserValue) Set(val *UserValue) {
	v.value = val
	v.isSet = true
}

func (v NullableUserValue) IsSet() bool {
	return v.isSet
}

func (v *NullableUserValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserValue(val *UserValue) *NullableUserValue {
	return &NullableUserValue{value: val, isSet: true}
}

func (v NullableUserValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


