/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the APIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIKeyResponse{}

// APIKeyResponse struct for APIKeyResponse
type APIKeyResponse struct {
	UserId string `json:"user_id"`
	KeyId string `json:"key_id"`
	Label string `json:"label"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	IsActive bool `json:"is_active"`
}

type _APIKeyResponse APIKeyResponse

// NewAPIKeyResponse instantiates a new APIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIKeyResponse(userId string, keyId string, label string, isActive bool) *APIKeyResponse {
	this := APIKeyResponse{}
	this.UserId = userId
	this.KeyId = keyId
	this.Label = label
	this.IsActive = isActive
	return &this
}

// NewAPIKeyResponseWithDefaults instantiates a new APIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIKeyResponseWithDefaults() *APIKeyResponse {
	this := APIKeyResponse{}
	return &this
}

// GetUserId returns the UserId field value
func (o *APIKeyResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *APIKeyResponse) SetUserId(v string) {
	o.UserId = v
}

// GetKeyId returns the KeyId field value
func (o *APIKeyResponse) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *APIKeyResponse) SetKeyId(v string) {
	o.KeyId = v
}

// GetLabel returns the Label field value
func (o *APIKeyResponse) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *APIKeyResponse) SetLabel(v string) {
	o.Label = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *APIKeyResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *APIKeyResponse) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *APIKeyResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetIsActive returns the IsActive field value
func (o *APIKeyResponse) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *APIKeyResponse) SetIsActive(v bool) {
	o.IsActive = v
}

func (o APIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["key_id"] = o.KeyId
	toSerialize["label"] = o.Label
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	toSerialize["is_active"] = o.IsActive
	return toSerialize, nil
}

func (o *APIKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"key_id",
		"label",
		"is_active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIKeyResponse := _APIKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIKeyResponse)

	if err != nil {
		return err
	}

	*o = APIKeyResponse(varAPIKeyResponse)

	return err
}

type NullableAPIKeyResponse struct {
	value *APIKeyResponse
	isSet bool
}

func (v NullableAPIKeyResponse) Get() *APIKeyResponse {
	return v.value
}

func (v *NullableAPIKeyResponse) Set(val *APIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIKeyResponse(val *APIKeyResponse) *NullableAPIKeyResponse {
	return &NullableAPIKeyResponse{value: val, isSet: true}
}

func (v NullableAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


