/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DepositArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepositArgs{}

// DepositArgs The non-signature arguments to the vault deposit() call. The remaining (v, r, s) arguments come from the permit signature the client obtains by signing the approval.
type DepositArgs struct {
	// Deposit quantity in USDC base units (10^-6 USDC), as a decimal string. Matches the permit's value.
	Quantity string `json:"quantity"`
	// The caller's user ID as 16 bytes, 0x-prefixed hex. Stored on-chain with the deposit and mapped back to the user by the indexer.
	UserId string `json:"user_id"`
	// The bytes32 client reference as a 0x-prefixed hex string. All zero bytes when not supplied.
	ClientReferenceId string `json:"client_reference_id"`
	// Unix timestamp (seconds), as a decimal string. Matches the permit's deadline exactly.
	Deadline string `json:"deadline"`
}

type _DepositArgs DepositArgs

// NewDepositArgs instantiates a new DepositArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepositArgs(quantity string, userId string, clientReferenceId string, deadline string) *DepositArgs {
	this := DepositArgs{}
	this.Quantity = quantity
	this.UserId = userId
	this.ClientReferenceId = clientReferenceId
	this.Deadline = deadline
	return &this
}

// NewDepositArgsWithDefaults instantiates a new DepositArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepositArgsWithDefaults() *DepositArgs {
	this := DepositArgs{}
	return &this
}

// GetQuantity returns the Quantity field value
func (o *DepositArgs) GetQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *DepositArgs) GetQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *DepositArgs) SetQuantity(v string) {
	o.Quantity = v
}

// GetUserId returns the UserId field value
func (o *DepositArgs) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *DepositArgs) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *DepositArgs) SetUserId(v string) {
	o.UserId = v
}

// GetClientReferenceId returns the ClientReferenceId field value
func (o *DepositArgs) GetClientReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value
// and a boolean to check if the value has been set.
func (o *DepositArgs) GetClientReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientReferenceId, true
}

// SetClientReferenceId sets field value
func (o *DepositArgs) SetClientReferenceId(v string) {
	o.ClientReferenceId = v
}

// GetDeadline returns the Deadline field value
func (o *DepositArgs) GetDeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value
// and a boolean to check if the value has been set.
func (o *DepositArgs) GetDeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deadline, true
}

// SetDeadline sets field value
func (o *DepositArgs) SetDeadline(v string) {
	o.Deadline = v
}

func (o DepositArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepositArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quantity"] = o.Quantity
	toSerialize["user_id"] = o.UserId
	toSerialize["client_reference_id"] = o.ClientReferenceId
	toSerialize["deadline"] = o.Deadline
	return toSerialize, nil
}

func (o *DepositArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quantity",
		"user_id",
		"client_reference_id",
		"deadline",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDepositArgs := _DepositArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDepositArgs)

	if err != nil {
		return err
	}

	*o = DepositArgs(varDepositArgs)

	return err
}

type NullableDepositArgs struct {
	value *DepositArgs
	isSet bool
}

func (v NullableDepositArgs) Get() *DepositArgs {
	return v.value
}

func (v *NullableDepositArgs) Set(val *DepositArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableDepositArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableDepositArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepositArgs(val *DepositArgs) *NullableDepositArgs {
	return &NullableDepositArgs{value: val, isSet: true}
}

func (v NullableDepositArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepositArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


