/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the OrderbookStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderbookStats{}

// OrderbookStats struct for OrderbookStats
type OrderbookStats struct {
	OrderBookId *string `json:"order_book_id,omitempty"`
	// Open price of the orderbook
	OpenPrice *string `json:"open_price,omitempty"`
	// Price of the most recent executed trade.
	LastPrice *string `json:"last_price,omitempty"`
	// Highest price of the orderbook in the last 24 hours.
	High24h *string `json:"high_24h,omitempty"`
	// Lowest price of the orderbook in the last 24 hours.
	Low24h *string `json:"low_24h,omitempty"`
	// Change in price of the orderbook in the last 24 hours.
	Change24h *string `json:"change_24h,omitempty"`
	// Change percentage in price of the orderbook in the last 24 hours.
	ChangePct24h *string `json:"change_pct_24h,omitempty"`
	// Total volume of the orderbook in the last 24 hours.
	Volume24hBase *string `json:"volume_24h_base,omitempty"`
	// Total volume of the orderbook in the last 24 hours in USD.
	Volume24hUsd *string `json:"volume_24h_usd,omitempty"`
}

// NewOrderbookStats instantiates a new OrderbookStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderbookStats() *OrderbookStats {
	this := OrderbookStats{}
	return &this
}

// NewOrderbookStatsWithDefaults instantiates a new OrderbookStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderbookStatsWithDefaults() *OrderbookStats {
	this := OrderbookStats{}
	return &this
}

// GetOrderBookId returns the OrderBookId field value if set, zero value otherwise.
func (o *OrderbookStats) GetOrderBookId() string {
	if o == nil || IsNil(o.OrderBookId) {
		var ret string
		return ret
	}
	return *o.OrderBookId
}

// GetOrderBookIdOk returns a tuple with the OrderBookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetOrderBookIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderBookId) {
		return nil, false
	}
	return o.OrderBookId, true
}

// HasOrderBookId returns a boolean if a field has been set.
func (o *OrderbookStats) HasOrderBookId() bool {
	if o != nil && !IsNil(o.OrderBookId) {
		return true
	}

	return false
}

// SetOrderBookId gets a reference to the given string and assigns it to the OrderBookId field.
func (o *OrderbookStats) SetOrderBookId(v string) {
	o.OrderBookId = &v
}

// GetOpenPrice returns the OpenPrice field value if set, zero value otherwise.
func (o *OrderbookStats) GetOpenPrice() string {
	if o == nil || IsNil(o.OpenPrice) {
		var ret string
		return ret
	}
	return *o.OpenPrice
}

// GetOpenPriceOk returns a tuple with the OpenPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetOpenPriceOk() (*string, bool) {
	if o == nil || IsNil(o.OpenPrice) {
		return nil, false
	}
	return o.OpenPrice, true
}

// HasOpenPrice returns a boolean if a field has been set.
func (o *OrderbookStats) HasOpenPrice() bool {
	if o != nil && !IsNil(o.OpenPrice) {
		return true
	}

	return false
}

// SetOpenPrice gets a reference to the given string and assigns it to the OpenPrice field.
func (o *OrderbookStats) SetOpenPrice(v string) {
	o.OpenPrice = &v
}

// GetLastPrice returns the LastPrice field value if set, zero value otherwise.
func (o *OrderbookStats) GetLastPrice() string {
	if o == nil || IsNil(o.LastPrice) {
		var ret string
		return ret
	}
	return *o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetLastPriceOk() (*string, bool) {
	if o == nil || IsNil(o.LastPrice) {
		return nil, false
	}
	return o.LastPrice, true
}

// HasLastPrice returns a boolean if a field has been set.
func (o *OrderbookStats) HasLastPrice() bool {
	if o != nil && !IsNil(o.LastPrice) {
		return true
	}

	return false
}

// SetLastPrice gets a reference to the given string and assigns it to the LastPrice field.
func (o *OrderbookStats) SetLastPrice(v string) {
	o.LastPrice = &v
}

// GetHigh24h returns the High24h field value if set, zero value otherwise.
func (o *OrderbookStats) GetHigh24h() string {
	if o == nil || IsNil(o.High24h) {
		var ret string
		return ret
	}
	return *o.High24h
}

// GetHigh24hOk returns a tuple with the High24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetHigh24hOk() (*string, bool) {
	if o == nil || IsNil(o.High24h) {
		return nil, false
	}
	return o.High24h, true
}

// HasHigh24h returns a boolean if a field has been set.
func (o *OrderbookStats) HasHigh24h() bool {
	if o != nil && !IsNil(o.High24h) {
		return true
	}

	return false
}

// SetHigh24h gets a reference to the given string and assigns it to the High24h field.
func (o *OrderbookStats) SetHigh24h(v string) {
	o.High24h = &v
}

// GetLow24h returns the Low24h field value if set, zero value otherwise.
func (o *OrderbookStats) GetLow24h() string {
	if o == nil || IsNil(o.Low24h) {
		var ret string
		return ret
	}
	return *o.Low24h
}

// GetLow24hOk returns a tuple with the Low24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetLow24hOk() (*string, bool) {
	if o == nil || IsNil(o.Low24h) {
		return nil, false
	}
	return o.Low24h, true
}

// HasLow24h returns a boolean if a field has been set.
func (o *OrderbookStats) HasLow24h() bool {
	if o != nil && !IsNil(o.Low24h) {
		return true
	}

	return false
}

// SetLow24h gets a reference to the given string and assigns it to the Low24h field.
func (o *OrderbookStats) SetLow24h(v string) {
	o.Low24h = &v
}

// GetChange24h returns the Change24h field value if set, zero value otherwise.
func (o *OrderbookStats) GetChange24h() string {
	if o == nil || IsNil(o.Change24h) {
		var ret string
		return ret
	}
	return *o.Change24h
}

// GetChange24hOk returns a tuple with the Change24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetChange24hOk() (*string, bool) {
	if o == nil || IsNil(o.Change24h) {
		return nil, false
	}
	return o.Change24h, true
}

// HasChange24h returns a boolean if a field has been set.
func (o *OrderbookStats) HasChange24h() bool {
	if o != nil && !IsNil(o.Change24h) {
		return true
	}

	return false
}

// SetChange24h gets a reference to the given string and assigns it to the Change24h field.
func (o *OrderbookStats) SetChange24h(v string) {
	o.Change24h = &v
}

// GetChangePct24h returns the ChangePct24h field value if set, zero value otherwise.
func (o *OrderbookStats) GetChangePct24h() string {
	if o == nil || IsNil(o.ChangePct24h) {
		var ret string
		return ret
	}
	return *o.ChangePct24h
}

// GetChangePct24hOk returns a tuple with the ChangePct24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetChangePct24hOk() (*string, bool) {
	if o == nil || IsNil(o.ChangePct24h) {
		return nil, false
	}
	return o.ChangePct24h, true
}

// HasChangePct24h returns a boolean if a field has been set.
func (o *OrderbookStats) HasChangePct24h() bool {
	if o != nil && !IsNil(o.ChangePct24h) {
		return true
	}

	return false
}

// SetChangePct24h gets a reference to the given string and assigns it to the ChangePct24h field.
func (o *OrderbookStats) SetChangePct24h(v string) {
	o.ChangePct24h = &v
}

// GetVolume24hBase returns the Volume24hBase field value if set, zero value otherwise.
func (o *OrderbookStats) GetVolume24hBase() string {
	if o == nil || IsNil(o.Volume24hBase) {
		var ret string
		return ret
	}
	return *o.Volume24hBase
}

// GetVolume24hBaseOk returns a tuple with the Volume24hBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetVolume24hBaseOk() (*string, bool) {
	if o == nil || IsNil(o.Volume24hBase) {
		return nil, false
	}
	return o.Volume24hBase, true
}

// HasVolume24hBase returns a boolean if a field has been set.
func (o *OrderbookStats) HasVolume24hBase() bool {
	if o != nil && !IsNil(o.Volume24hBase) {
		return true
	}

	return false
}

// SetVolume24hBase gets a reference to the given string and assigns it to the Volume24hBase field.
func (o *OrderbookStats) SetVolume24hBase(v string) {
	o.Volume24hBase = &v
}

// GetVolume24hUsd returns the Volume24hUsd field value if set, zero value otherwise.
func (o *OrderbookStats) GetVolume24hUsd() string {
	if o == nil || IsNil(o.Volume24hUsd) {
		var ret string
		return ret
	}
	return *o.Volume24hUsd
}

// GetVolume24hUsdOk returns a tuple with the Volume24hUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderbookStats) GetVolume24hUsdOk() (*string, bool) {
	if o == nil || IsNil(o.Volume24hUsd) {
		return nil, false
	}
	return o.Volume24hUsd, true
}

// HasVolume24hUsd returns a boolean if a field has been set.
func (o *OrderbookStats) HasVolume24hUsd() bool {
	if o != nil && !IsNil(o.Volume24hUsd) {
		return true
	}

	return false
}

// SetVolume24hUsd gets a reference to the given string and assigns it to the Volume24hUsd field.
func (o *OrderbookStats) SetVolume24hUsd(v string) {
	o.Volume24hUsd = &v
}

func (o OrderbookStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderbookStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderBookId) {
		toSerialize["order_book_id"] = o.OrderBookId
	}
	if !IsNil(o.OpenPrice) {
		toSerialize["open_price"] = o.OpenPrice
	}
	if !IsNil(o.LastPrice) {
		toSerialize["last_price"] = o.LastPrice
	}
	if !IsNil(o.High24h) {
		toSerialize["high_24h"] = o.High24h
	}
	if !IsNil(o.Low24h) {
		toSerialize["low_24h"] = o.Low24h
	}
	if !IsNil(o.Change24h) {
		toSerialize["change_24h"] = o.Change24h
	}
	if !IsNil(o.ChangePct24h) {
		toSerialize["change_pct_24h"] = o.ChangePct24h
	}
	if !IsNil(o.Volume24hBase) {
		toSerialize["volume_24h_base"] = o.Volume24hBase
	}
	if !IsNil(o.Volume24hUsd) {
		toSerialize["volume_24h_usd"] = o.Volume24hUsd
	}
	return toSerialize, nil
}

type NullableOrderbookStats struct {
	value *OrderbookStats
	isSet bool
}

func (v NullableOrderbookStats) Get() *OrderbookStats {
	return v.value
}

func (v *NullableOrderbookStats) Set(val *OrderbookStats) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderbookStats) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderbookStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderbookStats(val *OrderbookStats) *NullableOrderbookStats {
	return &NullableOrderbookStats{value: val, isSet: true}
}

func (v NullableOrderbookStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderbookStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


