/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type InlineResponse400 struct {
	Error_ string `json:"error,omitempty"`
	// The response data. Present for successful (2xx) responses.
	Data *interface{} `json:"data,omitempty"`
	Metadata *Metadata `json:"metadata,omitempty"`
}
