/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Trade type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Trade{}

// Trade struct for Trade
type Trade struct {
	TransactionId string `json:"transaction_id"`
	Asset0 string `json:"asset_0"`
	CreatedAt time.Time `json:"created_at"`
	OrderBookId string `json:"order_book_id"`
	OrderId string `json:"order_id"`
	OrderSeq int32 `json:"order_seq"`
	Price string `json:"price"`
	Quantity0 string `json:"quantity_0"`
	UserId string `json:"user_id"`
	Side Side `json:"side"`
	// If true, then this order is the aggressor (taker); otherwise it is the maker.
	AggressorIndicator bool `json:"aggressor_indicator"`
}

type _Trade Trade

// NewTrade instantiates a new Trade object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrade(transactionId string, asset0 string, createdAt time.Time, orderBookId string, orderId string, orderSeq int32, price string, quantity0 string, userId string, side Side, aggressorIndicator bool) *Trade {
	this := Trade{}
	this.TransactionId = transactionId
	this.Asset0 = asset0
	this.CreatedAt = createdAt
	this.OrderBookId = orderBookId
	this.OrderId = orderId
	this.OrderSeq = orderSeq
	this.Price = price
	this.Quantity0 = quantity0
	this.UserId = userId
	this.Side = side
	this.AggressorIndicator = aggressorIndicator
	return &this
}

// NewTradeWithDefaults instantiates a new Trade object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTradeWithDefaults() *Trade {
	this := Trade{}
	return &this
}

// GetTransactionId returns the TransactionId field value
func (o *Trade) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *Trade) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *Trade) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetAsset0 returns the Asset0 field value
func (o *Trade) GetAsset0() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset0
}

// GetAsset0Ok returns a tuple with the Asset0 field value
// and a boolean to check if the value has been set.
func (o *Trade) GetAsset0Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset0, true
}

// SetAsset0 sets field value
func (o *Trade) SetAsset0(v string) {
	o.Asset0 = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Trade) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Trade) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Trade) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetOrderBookId returns the OrderBookId field value
func (o *Trade) GetOrderBookId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderBookId
}

// GetOrderBookIdOk returns a tuple with the OrderBookId field value
// and a boolean to check if the value has been set.
func (o *Trade) GetOrderBookIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderBookId, true
}

// SetOrderBookId sets field value
func (o *Trade) SetOrderBookId(v string) {
	o.OrderBookId = v
}

// GetOrderId returns the OrderId field value
func (o *Trade) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *Trade) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *Trade) SetOrderId(v string) {
	o.OrderId = v
}

// GetOrderSeq returns the OrderSeq field value
func (o *Trade) GetOrderSeq() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrderSeq
}

// GetOrderSeqOk returns a tuple with the OrderSeq field value
// and a boolean to check if the value has been set.
func (o *Trade) GetOrderSeqOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderSeq, true
}

// SetOrderSeq sets field value
func (o *Trade) SetOrderSeq(v int32) {
	o.OrderSeq = v
}

// GetPrice returns the Price field value
func (o *Trade) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *Trade) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *Trade) SetPrice(v string) {
	o.Price = v
}

// GetQuantity0 returns the Quantity0 field value
func (o *Trade) GetQuantity0() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quantity0
}

// GetQuantity0Ok returns a tuple with the Quantity0 field value
// and a boolean to check if the value has been set.
func (o *Trade) GetQuantity0Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity0, true
}

// SetQuantity0 sets field value
func (o *Trade) SetQuantity0(v string) {
	o.Quantity0 = v
}

// GetUserId returns the UserId field value
func (o *Trade) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Trade) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Trade) SetUserId(v string) {
	o.UserId = v
}

// GetSide returns the Side field value
func (o *Trade) GetSide() Side {
	if o == nil {
		var ret Side
		return ret
	}

	return o.Side
}

// GetSideOk returns a tuple with the Side field value
// and a boolean to check if the value has been set.
func (o *Trade) GetSideOk() (*Side, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Side, true
}

// SetSide sets field value
func (o *Trade) SetSide(v Side) {
	o.Side = v
}

// GetAggressorIndicator returns the AggressorIndicator field value
func (o *Trade) GetAggressorIndicator() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AggressorIndicator
}

// GetAggressorIndicatorOk returns a tuple with the AggressorIndicator field value
// and a boolean to check if the value has been set.
func (o *Trade) GetAggressorIndicatorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggressorIndicator, true
}

// SetAggressorIndicator sets field value
func (o *Trade) SetAggressorIndicator(v bool) {
	o.AggressorIndicator = v
}

func (o Trade) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Trade) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["asset_0"] = o.Asset0
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["order_book_id"] = o.OrderBookId
	toSerialize["order_id"] = o.OrderId
	toSerialize["order_seq"] = o.OrderSeq
	toSerialize["price"] = o.Price
	toSerialize["quantity_0"] = o.Quantity0
	toSerialize["user_id"] = o.UserId
	toSerialize["side"] = o.Side
	toSerialize["aggressor_indicator"] = o.AggressorIndicator
	return toSerialize, nil
}

func (o *Trade) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_id",
		"asset_0",
		"created_at",
		"order_book_id",
		"order_id",
		"order_seq",
		"price",
		"quantity_0",
		"user_id",
		"side",
		"aggressor_indicator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrade := _Trade{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrade)

	if err != nil {
		return err
	}

	*o = Trade(varTrade)

	return err
}

type NullableTrade struct {
	value *Trade
	isSet bool
}

func (v NullableTrade) Get() *Trade {
	return v.value
}

func (v *NullableTrade) Set(val *Trade) {
	v.value = val
	v.isSet = true
}

func (v NullableTrade) IsSet() bool {
	return v.isSet
}

func (v *NullableTrade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrade(val *Trade) *NullableTrade {
	return &NullableTrade{value: val, isSet: true}
}

func (v NullableTrade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


