/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the StreamPositionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamPositionsResponse{}

// StreamPositionsResponse struct for StreamPositionsResponse
type StreamPositionsResponse struct {
}

// NewStreamPositionsResponse instantiates a new StreamPositionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamPositionsResponse() *StreamPositionsResponse {
	this := StreamPositionsResponse{}
	return &this
}

// NewStreamPositionsResponseWithDefaults instantiates a new StreamPositionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamPositionsResponseWithDefaults() *StreamPositionsResponse {
	this := StreamPositionsResponse{}
	return &this
}

func (o StreamPositionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamPositionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := make([]interface{}, len(o.Items))
	for i, item := range o.Items {
		toSerialize[i] = item
	}
	return toSerialize, nil
}

func (o *StreamPositionsResponse) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &o.Items)
}

type NullableStreamPositionsResponse struct {
	value StreamPositionsResponse
	isSet bool
}

func (v NullableStreamPositionsResponse) Get() StreamPositionsResponse {
	return v.value
}

func (v *NullableStreamPositionsResponse) Set(val StreamPositionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamPositionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamPositionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamPositionsResponse(val StreamPositionsResponse) *NullableStreamPositionsResponse {
	return &NullableStreamPositionsResponse{value: val, isSet: true}
}

func (v NullableStreamPositionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamPositionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


