/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the ClaimLeverageAccruedInterest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimLeverageAccruedInterest{}

// ClaimLeverageAccruedInterest struct for ClaimLeverageAccruedInterest
type ClaimLeverageAccruedInterest struct {
	TransactionId *string `json:"transaction_id,omitempty"`
	AssetId *string `json:"asset_id,omitempty"`
	PositionId *string `json:"position_id,omitempty"`
	CurrentAccruedInterestUsd *string `json:"current_accrued_interest_usd,omitempty"`
}

// NewClaimLeverageAccruedInterest instantiates a new ClaimLeverageAccruedInterest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimLeverageAccruedInterest() *ClaimLeverageAccruedInterest {
	this := ClaimLeverageAccruedInterest{}
	return &this
}

// NewClaimLeverageAccruedInterestWithDefaults instantiates a new ClaimLeverageAccruedInterest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimLeverageAccruedInterestWithDefaults() *ClaimLeverageAccruedInterest {
	this := ClaimLeverageAccruedInterest{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *ClaimLeverageAccruedInterest) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterest) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *ClaimLeverageAccruedInterest) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *ClaimLeverageAccruedInterest) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *ClaimLeverageAccruedInterest) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterest) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *ClaimLeverageAccruedInterest) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *ClaimLeverageAccruedInterest) SetAssetId(v string) {
	o.AssetId = &v
}

// GetPositionId returns the PositionId field value if set, zero value otherwise.
func (o *ClaimLeverageAccruedInterest) GetPositionId() string {
	if o == nil || IsNil(o.PositionId) {
		var ret string
		return ret
	}
	return *o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterest) GetPositionIdOk() (*string, bool) {
	if o == nil || IsNil(o.PositionId) {
		return nil, false
	}
	return o.PositionId, true
}

// HasPositionId returns a boolean if a field has been set.
func (o *ClaimLeverageAccruedInterest) HasPositionId() bool {
	if o != nil && !IsNil(o.PositionId) {
		return true
	}

	return false
}

// SetPositionId gets a reference to the given string and assigns it to the PositionId field.
func (o *ClaimLeverageAccruedInterest) SetPositionId(v string) {
	o.PositionId = &v
}

// GetCurrentAccruedInterestUsd returns the CurrentAccruedInterestUsd field value if set, zero value otherwise.
func (o *ClaimLeverageAccruedInterest) GetCurrentAccruedInterestUsd() string {
	if o == nil || IsNil(o.CurrentAccruedInterestUsd) {
		var ret string
		return ret
	}
	return *o.CurrentAccruedInterestUsd
}

// GetCurrentAccruedInterestUsdOk returns a tuple with the CurrentAccruedInterestUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterest) GetCurrentAccruedInterestUsdOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentAccruedInterestUsd) {
		return nil, false
	}
	return o.CurrentAccruedInterestUsd, true
}

// HasCurrentAccruedInterestUsd returns a boolean if a field has been set.
func (o *ClaimLeverageAccruedInterest) HasCurrentAccruedInterestUsd() bool {
	if o != nil && !IsNil(o.CurrentAccruedInterestUsd) {
		return true
	}

	return false
}

// SetCurrentAccruedInterestUsd gets a reference to the given string and assigns it to the CurrentAccruedInterestUsd field.
func (o *ClaimLeverageAccruedInterest) SetCurrentAccruedInterestUsd(v string) {
	o.CurrentAccruedInterestUsd = &v
}

func (o ClaimLeverageAccruedInterest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimLeverageAccruedInterest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	if !IsNil(o.PositionId) {
		toSerialize["position_id"] = o.PositionId
	}
	if !IsNil(o.CurrentAccruedInterestUsd) {
		toSerialize["current_accrued_interest_usd"] = o.CurrentAccruedInterestUsd
	}
	return toSerialize, nil
}

type NullableClaimLeverageAccruedInterest struct {
	value *ClaimLeverageAccruedInterest
	isSet bool
}

func (v NullableClaimLeverageAccruedInterest) Get() *ClaimLeverageAccruedInterest {
	return v.value
}

func (v *NullableClaimLeverageAccruedInterest) Set(val *ClaimLeverageAccruedInterest) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimLeverageAccruedInterest) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimLeverageAccruedInterest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimLeverageAccruedInterest(val *ClaimLeverageAccruedInterest) *NullableClaimLeverageAccruedInterest {
	return &NullableClaimLeverageAccruedInterest{value: val, isSet: true}
}

func (v NullableClaimLeverageAccruedInterest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimLeverageAccruedInterest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


