/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient
import (
	"time"
)

type CreateApiKeyRequest struct {
	Label string `json:"label,omitempty"`
	// Date at which the api-key will expire
	Expires time.Time `json:"expires,omitempty"`
}
