/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClaimLeverageAccruedInterestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimLeverageAccruedInterestRequest{}

// ClaimLeverageAccruedInterestRequest struct for ClaimLeverageAccruedInterestRequest
type ClaimLeverageAccruedInterestRequest struct {
	AssetId string `json:"asset_id"`
	PositionId string `json:"position_id"`
}

type _ClaimLeverageAccruedInterestRequest ClaimLeverageAccruedInterestRequest

// NewClaimLeverageAccruedInterestRequest instantiates a new ClaimLeverageAccruedInterestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimLeverageAccruedInterestRequest(assetId string, positionId string) *ClaimLeverageAccruedInterestRequest {
	this := ClaimLeverageAccruedInterestRequest{}
	this.AssetId = assetId
	this.PositionId = positionId
	return &this
}

// NewClaimLeverageAccruedInterestRequestWithDefaults instantiates a new ClaimLeverageAccruedInterestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimLeverageAccruedInterestRequestWithDefaults() *ClaimLeverageAccruedInterestRequest {
	this := ClaimLeverageAccruedInterestRequest{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *ClaimLeverageAccruedInterestRequest) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterestRequest) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *ClaimLeverageAccruedInterestRequest) SetAssetId(v string) {
	o.AssetId = v
}

// GetPositionId returns the PositionId field value
func (o *ClaimLeverageAccruedInterestRequest) GetPositionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterestRequest) GetPositionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionId, true
}

// SetPositionId sets field value
func (o *ClaimLeverageAccruedInterestRequest) SetPositionId(v string) {
	o.PositionId = v
}

func (o ClaimLeverageAccruedInterestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimLeverageAccruedInterestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_id"] = o.AssetId
	toSerialize["position_id"] = o.PositionId
	return toSerialize, nil
}

func (o *ClaimLeverageAccruedInterestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_id",
		"position_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimLeverageAccruedInterestRequest := _ClaimLeverageAccruedInterestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClaimLeverageAccruedInterestRequest)

	if err != nil {
		return err
	}

	*o = ClaimLeverageAccruedInterestRequest(varClaimLeverageAccruedInterestRequest)

	return err
}

type NullableClaimLeverageAccruedInterestRequest struct {
	value *ClaimLeverageAccruedInterestRequest
	isSet bool
}

func (v NullableClaimLeverageAccruedInterestRequest) Get() *ClaimLeverageAccruedInterestRequest {
	return v.value
}

func (v *NullableClaimLeverageAccruedInterestRequest) Set(val *ClaimLeverageAccruedInterestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimLeverageAccruedInterestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimLeverageAccruedInterestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimLeverageAccruedInterestRequest(val *ClaimLeverageAccruedInterestRequest) *NullableClaimLeverageAccruedInterestRequest {
	return &NullableClaimLeverageAccruedInterestRequest{value: val, isSet: true}
}

func (v NullableClaimLeverageAccruedInterestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimLeverageAccruedInterestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


