/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type UserRole string

// List of UserRole
const (
	PUBLIC_UserRole UserRole = "PUBLIC"
	SELF_UserRole UserRole = "SELF"
	ADMIN_UserRole UserRole = "ADMIN"
	BOND_PROVIDER_UserRole UserRole = "BOND_PROVIDER"
	LIQUIDITY_PROVIDER_UserRole UserRole = "LIQUIDITY_PROVIDER"
	TRADER_UserRole UserRole = "TRADER"
)
