/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the IsolatedPosition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsolatedPosition{}

// IsolatedPosition struct for IsolatedPosition
type IsolatedPosition struct {
	GlobalPositionId *string `json:"global_position_id,omitempty"`
	IsolatedPositionId *string `json:"isolated_position_id,omitempty"`
	TransactionId *string `json:"transaction_id,omitempty"`
}

// NewIsolatedPosition instantiates a new IsolatedPosition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsolatedPosition() *IsolatedPosition {
	this := IsolatedPosition{}
	return &this
}

// NewIsolatedPositionWithDefaults instantiates a new IsolatedPosition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsolatedPositionWithDefaults() *IsolatedPosition {
	this := IsolatedPosition{}
	return &this
}

// GetGlobalPositionId returns the GlobalPositionId field value if set, zero value otherwise.
func (o *IsolatedPosition) GetGlobalPositionId() string {
	if o == nil || IsNil(o.GlobalPositionId) {
		var ret string
		return ret
	}
	return *o.GlobalPositionId
}

// GetGlobalPositionIdOk returns a tuple with the GlobalPositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedPosition) GetGlobalPositionIdOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalPositionId) {
		return nil, false
	}
	return o.GlobalPositionId, true
}

// HasGlobalPositionId returns a boolean if a field has been set.
func (o *IsolatedPosition) HasGlobalPositionId() bool {
	if o != nil && !IsNil(o.GlobalPositionId) {
		return true
	}

	return false
}

// SetGlobalPositionId gets a reference to the given string and assigns it to the GlobalPositionId field.
func (o *IsolatedPosition) SetGlobalPositionId(v string) {
	o.GlobalPositionId = &v
}

// GetIsolatedPositionId returns the IsolatedPositionId field value if set, zero value otherwise.
func (o *IsolatedPosition) GetIsolatedPositionId() string {
	if o == nil || IsNil(o.IsolatedPositionId) {
		var ret string
		return ret
	}
	return *o.IsolatedPositionId
}

// GetIsolatedPositionIdOk returns a tuple with the IsolatedPositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedPosition) GetIsolatedPositionIdOk() (*string, bool) {
	if o == nil || IsNil(o.IsolatedPositionId) {
		return nil, false
	}
	return o.IsolatedPositionId, true
}

// HasIsolatedPositionId returns a boolean if a field has been set.
func (o *IsolatedPosition) HasIsolatedPositionId() bool {
	if o != nil && !IsNil(o.IsolatedPositionId) {
		return true
	}

	return false
}

// SetIsolatedPositionId gets a reference to the given string and assigns it to the IsolatedPositionId field.
func (o *IsolatedPosition) SetIsolatedPositionId(v string) {
	o.IsolatedPositionId = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *IsolatedPosition) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsolatedPosition) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *IsolatedPosition) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *IsolatedPosition) SetTransactionId(v string) {
	o.TransactionId = &v
}

func (o IsolatedPosition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsolatedPosition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalPositionId) {
		toSerialize["global_position_id"] = o.GlobalPositionId
	}
	if !IsNil(o.IsolatedPositionId) {
		toSerialize["isolated_position_id"] = o.IsolatedPositionId
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	return toSerialize, nil
}

type NullableIsolatedPosition struct {
	value *IsolatedPosition
	isSet bool
}

func (v NullableIsolatedPosition) Get() *IsolatedPosition {
	return v.value
}

func (v *NullableIsolatedPosition) Set(val *IsolatedPosition) {
	v.value = val
	v.isSet = true
}

func (v NullableIsolatedPosition) IsSet() bool {
	return v.isSet
}

func (v *NullableIsolatedPosition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsolatedPosition(val *IsolatedPosition) *NullableIsolatedPosition {
	return &NullableIsolatedPosition{value: val, isSet: true}
}

func (v NullableIsolatedPosition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsolatedPosition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


