/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the UserDeletedResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDeletedResponseEnvelope{}

// UserDeletedResponseEnvelope struct for UserDeletedResponseEnvelope
type UserDeletedResponseEnvelope struct {
	Data *string `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	// Metadata about the response, including status code and trace information.
	Metadata *Metadata `json:"metadata,omitempty"`
}

// NewUserDeletedResponseEnvelope instantiates a new UserDeletedResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDeletedResponseEnvelope() *UserDeletedResponseEnvelope {
	this := UserDeletedResponseEnvelope{}
	return &this
}

// NewUserDeletedResponseEnvelopeWithDefaults instantiates a new UserDeletedResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDeletedResponseEnvelopeWithDefaults() *UserDeletedResponseEnvelope {
	this := UserDeletedResponseEnvelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UserDeletedResponseEnvelope) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDeletedResponseEnvelope) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UserDeletedResponseEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *UserDeletedResponseEnvelope) SetData(v string) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UserDeletedResponseEnvelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDeletedResponseEnvelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UserDeletedResponseEnvelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UserDeletedResponseEnvelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UserDeletedResponseEnvelope) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDeletedResponseEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UserDeletedResponseEnvelope) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *UserDeletedResponseEnvelope) SetMetadata(v Metadata) {
	o.Metadata = &v
}

func (o UserDeletedResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDeletedResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableUserDeletedResponseEnvelope struct {
	value *UserDeletedResponseEnvelope
	isSet bool
}

func (v NullableUserDeletedResponseEnvelope) Get() *UserDeletedResponseEnvelope {
	return v.value
}

func (v *NullableUserDeletedResponseEnvelope) Set(val *UserDeletedResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDeletedResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDeletedResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDeletedResponseEnvelope(val *UserDeletedResponseEnvelope) *NullableUserDeletedResponseEnvelope {
	return &NullableUserDeletedResponseEnvelope{value: val, isSet: true}
}

func (v NullableUserDeletedResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDeletedResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


