/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type UpdateOrderBookRequest struct {
	OrderBookId string `json:"order_book_id,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	FeeFactor float64 `json:"fee_factor,omitempty"`
	InitialAssetsRatio float64 `json:"initial_assets_ratio,omitempty"`
	PriceDisplayMultiplier float64 `json:"price_display_multiplier,omitempty"`
	TickSize float64 `json:"tick_size,omitempty"`
	BaseQuantity float64 `json:"base_quantity,omitempty"`
	QuoteQuantity float64 `json:"quote_quantity,omitempty"`
}
