/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

// Request body for PUT /user/{id} (admin-only): update a user's details.
type UpdateUserRequest struct {
	Email *UpdateFieldString `json:"email,omitempty"`
	Name *UpdateFieldString `json:"name,omitempty"`
	NativeAssetId *UpdateFieldUuid `json:"native_asset_id,omitempty"`
	PhotoUrl *UpdateFieldString `json:"photo_url,omitempty"`
	Provider *UpdateFieldString `json:"provider,omitempty"`
	ProviderId *UpdateFieldUuid `json:"provider_id,omitempty"`
	Roles *UpdateFieldString `json:"roles,omitempty"`
	Timezone *UpdateFieldString `json:"timezone,omitempty"`
	VerifiedAt *UpdateFieldDateTime `json:"verified_at,omitempty"`
}
