/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient
import (
	"time"
)

type User struct {
	Id string `json:"id,omitempty"`
	ClosedAt time.Time `json:"closed_at,omitempty"`
	DisabledAt time.Time `json:"disabled_at,omitempty"`
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
	NativeAssetId string `json:"native_asset_id,omitempty"`
	PhotoUrl string `json:"photo_url,omitempty"`
	Provider string `json:"provider,omitempty"`
	ProviderId string `json:"provider_id,omitempty"`
	Roles []string `json:"roles,omitempty"`
	// User's timezone, e.g., 'America/New_York', or an offset.
	Timezone string `json:"timezone,omitempty"`
	// timezone offset in seconds
	TimezoneOffset int32 `json:"timezone_offset,omitempty"`
}
