/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AffiliateReferralReportEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffiliateReferralReportEnvelope{}

// AffiliateReferralReportEnvelope struct for AffiliateReferralReportEnvelope
type AffiliateReferralReportEnvelope struct {
	Data AffiliateReferralReport `json:"data"`
	Metadata Metadata `json:"metadata"`
}

type _AffiliateReferralReportEnvelope AffiliateReferralReportEnvelope

// NewAffiliateReferralReportEnvelope instantiates a new AffiliateReferralReportEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateReferralReportEnvelope(data AffiliateReferralReport, metadata Metadata) *AffiliateReferralReportEnvelope {
	this := AffiliateReferralReportEnvelope{}
	this.Data = data
	this.Metadata = metadata
	return &this
}

// NewAffiliateReferralReportEnvelopeWithDefaults instantiates a new AffiliateReferralReportEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateReferralReportEnvelopeWithDefaults() *AffiliateReferralReportEnvelope {
	this := AffiliateReferralReportEnvelope{}
	return &this
}

// GetData returns the Data field value
func (o *AffiliateReferralReportEnvelope) GetData() AffiliateReferralReport {
	if o == nil {
		var ret AffiliateReferralReport
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AffiliateReferralReportEnvelope) GetDataOk() (*AffiliateReferralReport, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AffiliateReferralReportEnvelope) SetData(v AffiliateReferralReport) {
	o.Data = v
}

// GetMetadata returns the Metadata field value
func (o *AffiliateReferralReportEnvelope) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *AffiliateReferralReportEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *AffiliateReferralReportEnvelope) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o AffiliateReferralReportEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AffiliateReferralReportEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *AffiliateReferralReportEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAffiliateReferralReportEnvelope := _AffiliateReferralReportEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAffiliateReferralReportEnvelope)

	if err != nil {
		return err
	}

	*o = AffiliateReferralReportEnvelope(varAffiliateReferralReportEnvelope)

	return err
}

type NullableAffiliateReferralReportEnvelope struct {
	value *AffiliateReferralReportEnvelope
	isSet bool
}

func (v NullableAffiliateReferralReportEnvelope) Get() *AffiliateReferralReportEnvelope {
	return v.value
}

func (v *NullableAffiliateReferralReportEnvelope) Set(val *AffiliateReferralReportEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateReferralReportEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateReferralReportEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateReferralReportEnvelope(val *AffiliateReferralReportEnvelope) *NullableAffiliateReferralReportEnvelope {
	return &NullableAffiliateReferralReportEnvelope{value: val, isSet: true}
}

func (v NullableAffiliateReferralReportEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateReferralReportEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


