/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the CreateIntegratorUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIntegratorUserRequest{}

// CreateIntegratorUserRequest struct for CreateIntegratorUserRequest
type CreateIntegratorUserRequest struct {
	Email *string
	FirstName *string
	LastName *string
	CountryOfDomicile *CountryCode
	NativeAssetId *string
	PhotoUrl *string
	Provider *string
	ProviderId *string
	Timezone *string
}

// NewCreateIntegratorUserRequest instantiates a new CreateIntegratorUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIntegratorUserRequest() *CreateIntegratorUserRequest {
	this := CreateIntegratorUserRequest{}
	return &this
}

// NewCreateIntegratorUserRequestWithDefaults instantiates a new CreateIntegratorUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIntegratorUserRequestWithDefaults() *CreateIntegratorUserRequest {
	this := CreateIntegratorUserRequest{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateIntegratorUserRequest) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *CreateIntegratorUserRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *CreateIntegratorUserRequest) SetLastName(v string) {
	o.LastName = &v
}

// GetCountryOfDomicile returns the CountryOfDomicile field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetCountryOfDomicile() CountryCode {
	if o == nil || IsNil(o.CountryOfDomicile) {
		var ret CountryCode
		return ret
	}
	return *o.CountryOfDomicile
}

// GetCountryOfDomicileOk returns a tuple with the CountryOfDomicile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetCountryOfDomicileOk() (*CountryCode, bool) {
	if o == nil || IsNil(o.CountryOfDomicile) {
		return nil, false
	}
	return o.CountryOfDomicile, true
}

// HasCountryOfDomicile returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasCountryOfDomicile() bool {
	if o != nil && !IsNil(o.CountryOfDomicile) {
		return true
	}

	return false
}

// SetCountryOfDomicile gets a reference to the given CountryCode and assigns it to the CountryOfDomicile field.
func (o *CreateIntegratorUserRequest) SetCountryOfDomicile(v CountryCode) {
	o.CountryOfDomicile = &v
}

// GetNativeAssetId returns the NativeAssetId field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetNativeAssetId() string {
	if o == nil || IsNil(o.NativeAssetId) {
		var ret string
		return ret
	}
	return *o.NativeAssetId
}

// GetNativeAssetIdOk returns a tuple with the NativeAssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetNativeAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.NativeAssetId) {
		return nil, false
	}
	return o.NativeAssetId, true
}

// HasNativeAssetId returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasNativeAssetId() bool {
	if o != nil && !IsNil(o.NativeAssetId) {
		return true
	}

	return false
}

// SetNativeAssetId gets a reference to the given string and assigns it to the NativeAssetId field.
func (o *CreateIntegratorUserRequest) SetNativeAssetId(v string) {
	o.NativeAssetId = &v
}

// GetPhotoUrl returns the PhotoUrl field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetPhotoUrl() string {
	if o == nil || IsNil(o.PhotoUrl) {
		var ret string
		return ret
	}
	return *o.PhotoUrl
}

// GetPhotoUrlOk returns a tuple with the PhotoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetPhotoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PhotoUrl) {
		return nil, false
	}
	return o.PhotoUrl, true
}

// HasPhotoUrl returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasPhotoUrl() bool {
	if o != nil && !IsNil(o.PhotoUrl) {
		return true
	}

	return false
}

// SetPhotoUrl gets a reference to the given string and assigns it to the PhotoUrl field.
func (o *CreateIntegratorUserRequest) SetPhotoUrl(v string) {
	o.PhotoUrl = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *CreateIntegratorUserRequest) SetProvider(v string) {
	o.Provider = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId) {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *CreateIntegratorUserRequest) SetProviderId(v string) {
	o.ProviderId = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *CreateIntegratorUserRequest) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegratorUserRequest) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *CreateIntegratorUserRequest) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *CreateIntegratorUserRequest) SetTimezone(v string) {
	o.Timezone = &v
}

func (o CreateIntegratorUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIntegratorUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.CountryOfDomicile) {
		toSerialize["country_of_domicile"] = o.CountryOfDomicile
	}
	if !IsNil(o.NativeAssetId) {
		toSerialize["native_asset_id"] = o.NativeAssetId
	}
	if !IsNil(o.PhotoUrl) {
		toSerialize["photo_url"] = o.PhotoUrl
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.ProviderId) {
		toSerialize["provider_id"] = o.ProviderId
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	return toSerialize, nil
}

type NullableCreateIntegratorUserRequest struct {
	value *CreateIntegratorUserRequest
	isSet bool
}

func (v NullableCreateIntegratorUserRequest) Get() *CreateIntegratorUserRequest {
	return v.value
}

func (v *NullableCreateIntegratorUserRequest) Set(val *CreateIntegratorUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIntegratorUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIntegratorUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIntegratorUserRequest(val *CreateIntegratorUserRequest) *NullableCreateIntegratorUserRequest {
	return &NullableCreateIntegratorUserRequest{value: val, isSet: true}
}

func (v NullableCreateIntegratorUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIntegratorUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


