/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddTradingChallengeUsersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTradingChallengeUsersRequest{}

// AddTradingChallengeUsersRequest struct for AddTradingChallengeUsersRequest
type AddTradingChallengeUsersRequest struct {
	TradingChallengeId string `json:"trading_challenge_id"`
	Users []string `json:"users"`
}

type _AddTradingChallengeUsersRequest AddTradingChallengeUsersRequest

// NewAddTradingChallengeUsersRequest instantiates a new AddTradingChallengeUsersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTradingChallengeUsersRequest(tradingChallengeId string, users []string) *AddTradingChallengeUsersRequest {
	this := AddTradingChallengeUsersRequest{}
	this.TradingChallengeId = tradingChallengeId
	this.Users = users
	return &this
}

// NewAddTradingChallengeUsersRequestWithDefaults instantiates a new AddTradingChallengeUsersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTradingChallengeUsersRequestWithDefaults() *AddTradingChallengeUsersRequest {
	this := AddTradingChallengeUsersRequest{}
	return &this
}

// GetTradingChallengeId returns the TradingChallengeId field value
func (o *AddTradingChallengeUsersRequest) GetTradingChallengeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradingChallengeId
}

// GetTradingChallengeIdOk returns a tuple with the TradingChallengeId field value
// and a boolean to check if the value has been set.
func (o *AddTradingChallengeUsersRequest) GetTradingChallengeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradingChallengeId, true
}

// SetTradingChallengeId sets field value
func (o *AddTradingChallengeUsersRequest) SetTradingChallengeId(v string) {
	o.TradingChallengeId = v
}

// GetUsers returns the Users field value
func (o *AddTradingChallengeUsersRequest) GetUsers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *AddTradingChallengeUsersRequest) GetUsersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *AddTradingChallengeUsersRequest) SetUsers(v []string) {
	o.Users = v
}

func (o AddTradingChallengeUsersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTradingChallengeUsersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trading_challenge_id"] = o.TradingChallengeId
	toSerialize["users"] = o.Users
	return toSerialize, nil
}

func (o *AddTradingChallengeUsersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trading_challenge_id",
		"users",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddTradingChallengeUsersRequest := _AddTradingChallengeUsersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddTradingChallengeUsersRequest)

	if err != nil {
		return err
	}

	*o = AddTradingChallengeUsersRequest(varAddTradingChallengeUsersRequest)

	return err
}

type NullableAddTradingChallengeUsersRequest struct {
	value *AddTradingChallengeUsersRequest
	isSet bool
}

func (v NullableAddTradingChallengeUsersRequest) Get() *AddTradingChallengeUsersRequest {
	return v.value
}

func (v *NullableAddTradingChallengeUsersRequest) Set(val *AddTradingChallengeUsersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTradingChallengeUsersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTradingChallengeUsersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTradingChallengeUsersRequest(val *AddTradingChallengeUsersRequest) *NullableAddTradingChallengeUsersRequest {
	return &NullableAddTradingChallengeUsersRequest{value: val, isSet: true}
}

func (v NullableAddTradingChallengeUsersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTradingChallengeUsersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


