/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the StreamTransactionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamTransactionsResponse{}

// StreamTransactionsResponse struct for StreamTransactionsResponse
type StreamTransactionsResponse struct {
	StreamTransactionsEntries []StreamTransactionsEntry `json:"stream_transactions_entries,omitempty"`
}

// NewStreamTransactionsResponse instantiates a new StreamTransactionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamTransactionsResponse() *StreamTransactionsResponse {
	this := StreamTransactionsResponse{}
	return &this
}

// NewStreamTransactionsResponseWithDefaults instantiates a new StreamTransactionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamTransactionsResponseWithDefaults() *StreamTransactionsResponse {
	this := StreamTransactionsResponse{}
	return &this
}

// GetStreamTransactionsEntries returns the StreamTransactionsEntries field value if set, zero value otherwise.
func (o *StreamTransactionsResponse) GetStreamTransactionsEntries() []StreamTransactionsEntry {
	if o == nil || IsNil(o.StreamTransactionsEntries) {
		var ret []StreamTransactionsEntry
		return ret
	}
	return o.StreamTransactionsEntries
}

// GetStreamTransactionsEntriesOk returns a tuple with the StreamTransactionsEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamTransactionsResponse) GetStreamTransactionsEntriesOk() ([]StreamTransactionsEntry, bool) {
	if o == nil || IsNil(o.StreamTransactionsEntries) {
		return nil, false
	}
	return o.StreamTransactionsEntries, true
}

// HasStreamTransactionsEntries returns a boolean if a field has been set.
func (o *StreamTransactionsResponse) HasStreamTransactionsEntries() bool {
	if o != nil && !IsNil(o.StreamTransactionsEntries) {
		return true
	}

	return false
}

// SetStreamTransactionsEntries gets a reference to the given []StreamTransactionsEntry and assigns it to the StreamTransactionsEntries field.
func (o *StreamTransactionsResponse) SetStreamTransactionsEntries(v []StreamTransactionsEntry) {
	o.StreamTransactionsEntries = v
}

func (o StreamTransactionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamTransactionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StreamTransactionsEntries) {
		toSerialize["stream_transactions_entries"] = o.StreamTransactionsEntries
	}
	return toSerialize, nil
}

type NullableStreamTransactionsResponse struct {
	value *StreamTransactionsResponse
	isSet bool
}

func (v NullableStreamTransactionsResponse) Get() *StreamTransactionsResponse {
	return v.value
}

func (v *NullableStreamTransactionsResponse) Set(val *StreamTransactionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamTransactionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamTransactionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamTransactionsResponse(val *StreamTransactionsResponse) *NullableStreamTransactionsResponse {
	return &NullableStreamTransactionsResponse{value: val, isSet: true}
}

func (v NullableStreamTransactionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamTransactionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


