/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the UserInterest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInterest{}

// UserInterest struct for UserInterest
type UserInterest struct {
	Available *map[string]int32 `json:"available,omitempty"`
	Value *map[string]string `json:"value,omitempty"`
}

// NewUserInterest instantiates a new UserInterest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInterest() *UserInterest {
	this := UserInterest{}
	return &this
}

// NewUserInterestWithDefaults instantiates a new UserInterest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInterestWithDefaults() *UserInterest {
	this := UserInterest{}
	return &this
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *UserInterest) GetAvailable() map[string]int32 {
	if o == nil || IsNil(o.Available) {
		var ret map[string]int32
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInterest) GetAvailableOk() (*map[string]int32, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *UserInterest) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given map[string]int32 and assigns it to the Available field.
func (o *UserInterest) SetAvailable(v map[string]int32) {
	o.Available = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UserInterest) GetValue() map[string]string {
	if o == nil || IsNil(o.Value) {
		var ret map[string]string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInterest) GetValueOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UserInterest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]string and assigns it to the Value field.
func (o *UserInterest) SetValue(v map[string]string) {
	o.Value = &v
}

func (o UserInterest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInterest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableUserInterest struct {
	value *UserInterest
	isSet bool
}

func (v NullableUserInterest) Get() *UserInterest {
	return v.value
}

func (v *NullableUserInterest) Set(val *UserInterest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInterest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInterest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInterest(val *UserInterest) *NullableUserInterest {
	return &NullableUserInterest{value: val, isSet: true}
}

func (v NullableUserInterest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInterest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


