/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// UpdateAffiliateProgramRequestIsActive - Inactive programs retain registrations, but cannot issue or resolve codes. Omitted, null, or update=false leaves the field unchanged.
type UpdateAffiliateProgramRequestIsActive struct {
	UpdateFieldBoolean *UpdateFieldBoolean
	Bool *bool
}

// UpdateFieldBooleanAsUpdateAffiliateProgramRequestIsActive is a convenience function that returns UpdateFieldBoolean wrapped in UpdateAffiliateProgramRequestIsActive
func UpdateFieldBooleanAsUpdateAffiliateProgramRequestIsActive(v *UpdateFieldBoolean) UpdateAffiliateProgramRequestIsActive {
	return UpdateAffiliateProgramRequestIsActive{
		UpdateFieldBoolean: v,
	}
}

// boolAsUpdateAffiliateProgramRequestIsActive is a convenience function that returns bool wrapped in UpdateAffiliateProgramRequestIsActive
func BoolAsUpdateAffiliateProgramRequestIsActive(v *bool) UpdateAffiliateProgramRequestIsActive {
	return UpdateAffiliateProgramRequestIsActive{
		Bool: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *UpdateAffiliateProgramRequestIsActive) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UpdateFieldBoolean
	err = newStrictDecoder(data).Decode(&dst.UpdateFieldBoolean)
	if err == nil {
		jsonUpdateFieldBoolean, _ := json.Marshal(dst.UpdateFieldBoolean)
		if string(jsonUpdateFieldBoolean) == "{}" { // empty struct
			dst.UpdateFieldBoolean = nil
		} else {
			if err = validator.Validate(dst.UpdateFieldBoolean); err != nil {
				dst.UpdateFieldBoolean = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateFieldBoolean = nil
	}

	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UpdateFieldBoolean = nil
		dst.Bool = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UpdateAffiliateProgramRequestIsActive)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UpdateAffiliateProgramRequestIsActive)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateAffiliateProgramRequestIsActive) MarshalJSON() ([]byte, error) {
	if src.UpdateFieldBoolean != nil {
		return json.Marshal(&src.UpdateFieldBoolean)
	}

	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UpdateAffiliateProgramRequestIsActive) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.UpdateFieldBoolean != nil {
		return obj.UpdateFieldBoolean
	}

	if obj.Bool != nil {
		return obj.Bool
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UpdateAffiliateProgramRequestIsActive) GetActualInstanceValue() (interface{}) {
	if obj.UpdateFieldBoolean != nil {
		return *obj.UpdateFieldBoolean
	}

	if obj.Bool != nil {
		return *obj.Bool
	}

	// all schemas are nil
	return nil
}

type NullableUpdateAffiliateProgramRequestIsActive struct {
	value *UpdateAffiliateProgramRequestIsActive
	isSet bool
}

func (v NullableUpdateAffiliateProgramRequestIsActive) Get() *UpdateAffiliateProgramRequestIsActive {
	return v.value
}

func (v *NullableUpdateAffiliateProgramRequestIsActive) Set(val *UpdateAffiliateProgramRequestIsActive) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAffiliateProgramRequestIsActive) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAffiliateProgramRequestIsActive) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAffiliateProgramRequestIsActive(val *UpdateAffiliateProgramRequestIsActive) *NullableUpdateAffiliateProgramRequestIsActive {
	return &NullableUpdateAffiliateProgramRequestIsActive{value: val, isSet: true}
}

func (v NullableUpdateAffiliateProgramRequestIsActive) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAffiliateProgramRequestIsActive) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


