/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TerminateTradingChallengeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminateTradingChallengeResponse{}

// TerminateTradingChallengeResponse struct for TerminateTradingChallengeResponse
type TerminateTradingChallengeResponse struct {
	TradingChallengeId string `json:"trading_challenge_id"`
	UserId string `json:"user_id"`
	Status string `json:"status"`
}

type _TerminateTradingChallengeResponse TerminateTradingChallengeResponse

// NewTerminateTradingChallengeResponse instantiates a new TerminateTradingChallengeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminateTradingChallengeResponse(tradingChallengeId string, userId string, status string) *TerminateTradingChallengeResponse {
	this := TerminateTradingChallengeResponse{}
	this.TradingChallengeId = tradingChallengeId
	this.UserId = userId
	this.Status = status
	return &this
}

// NewTerminateTradingChallengeResponseWithDefaults instantiates a new TerminateTradingChallengeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminateTradingChallengeResponseWithDefaults() *TerminateTradingChallengeResponse {
	this := TerminateTradingChallengeResponse{}
	return &this
}

// GetTradingChallengeId returns the TradingChallengeId field value
func (o *TerminateTradingChallengeResponse) GetTradingChallengeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradingChallengeId
}

// GetTradingChallengeIdOk returns a tuple with the TradingChallengeId field value
// and a boolean to check if the value has been set.
func (o *TerminateTradingChallengeResponse) GetTradingChallengeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradingChallengeId, true
}

// SetTradingChallengeId sets field value
func (o *TerminateTradingChallengeResponse) SetTradingChallengeId(v string) {
	o.TradingChallengeId = v
}

// GetUserId returns the UserId field value
func (o *TerminateTradingChallengeResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *TerminateTradingChallengeResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *TerminateTradingChallengeResponse) SetUserId(v string) {
	o.UserId = v
}

// GetStatus returns the Status field value
func (o *TerminateTradingChallengeResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TerminateTradingChallengeResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TerminateTradingChallengeResponse) SetStatus(v string) {
	o.Status = v
}

func (o TerminateTradingChallengeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminateTradingChallengeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trading_challenge_id"] = o.TradingChallengeId
	toSerialize["user_id"] = o.UserId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *TerminateTradingChallengeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trading_challenge_id",
		"user_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerminateTradingChallengeResponse := _TerminateTradingChallengeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerminateTradingChallengeResponse)

	if err != nil {
		return err
	}

	*o = TerminateTradingChallengeResponse(varTerminateTradingChallengeResponse)

	return err
}

type NullableTerminateTradingChallengeResponse struct {
	value *TerminateTradingChallengeResponse
	isSet bool
}

func (v NullableTerminateTradingChallengeResponse) Get() *TerminateTradingChallengeResponse {
	return v.value
}

func (v *NullableTerminateTradingChallengeResponse) Set(val *TerminateTradingChallengeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminateTradingChallengeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminateTradingChallengeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminateTradingChallengeResponse(val *TerminateTradingChallengeResponse) *NullableTerminateTradingChallengeResponse {
	return &NullableTerminateTradingChallengeResponse{value: val, isSet: true}
}

func (v NullableTerminateTradingChallengeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminateTradingChallengeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


