/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AffiliateCashFlow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffiliateCashFlow{}

// AffiliateCashFlow struct for AffiliateCashFlow
type AffiliateCashFlow struct {
	Id string `json:"id"`
	Kind string `json:"kind"`
	CreatedAt time.Time `json:"created_at"`
	AssetId string `json:"asset_id"`
	AssetSymbol string `json:"asset_symbol"`
	// Decimal value, without binary floating-point rounding.
	Amount string `json:"amount"`
}

type _AffiliateCashFlow AffiliateCashFlow

// NewAffiliateCashFlow instantiates a new AffiliateCashFlow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateCashFlow(id string, kind string, createdAt time.Time, assetId string, assetSymbol string, amount string) *AffiliateCashFlow {
	this := AffiliateCashFlow{}
	this.Id = id
	this.Kind = kind
	this.CreatedAt = createdAt
	this.AssetId = assetId
	this.AssetSymbol = assetSymbol
	this.Amount = amount
	return &this
}

// NewAffiliateCashFlowWithDefaults instantiates a new AffiliateCashFlow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateCashFlowWithDefaults() *AffiliateCashFlow {
	this := AffiliateCashFlow{}
	return &this
}

// GetId returns the Id field value
func (o *AffiliateCashFlow) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AffiliateCashFlow) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AffiliateCashFlow) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *AffiliateCashFlow) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AffiliateCashFlow) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AffiliateCashFlow) SetKind(v string) {
	o.Kind = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AffiliateCashFlow) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AffiliateCashFlow) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AffiliateCashFlow) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetAssetId returns the AssetId field value
func (o *AffiliateCashFlow) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *AffiliateCashFlow) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *AffiliateCashFlow) SetAssetId(v string) {
	o.AssetId = v
}

// GetAssetSymbol returns the AssetSymbol field value
func (o *AffiliateCashFlow) GetAssetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetSymbol
}

// GetAssetSymbolOk returns a tuple with the AssetSymbol field value
// and a boolean to check if the value has been set.
func (o *AffiliateCashFlow) GetAssetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetSymbol, true
}

// SetAssetSymbol sets field value
func (o *AffiliateCashFlow) SetAssetSymbol(v string) {
	o.AssetSymbol = v
}

// GetAmount returns the Amount field value
func (o *AffiliateCashFlow) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AffiliateCashFlow) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AffiliateCashFlow) SetAmount(v string) {
	o.Amount = v
}

func (o AffiliateCashFlow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AffiliateCashFlow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["asset_id"] = o.AssetId
	toSerialize["asset_symbol"] = o.AssetSymbol
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *AffiliateCashFlow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"kind",
		"created_at",
		"asset_id",
		"asset_symbol",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAffiliateCashFlow := _AffiliateCashFlow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAffiliateCashFlow)

	if err != nil {
		return err
	}

	*o = AffiliateCashFlow(varAffiliateCashFlow)

	return err
}

type NullableAffiliateCashFlow struct {
	value *AffiliateCashFlow
	isSet bool
}

func (v NullableAffiliateCashFlow) Get() *AffiliateCashFlow {
	return v.value
}

func (v *NullableAffiliateCashFlow) Set(val *AffiliateCashFlow) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateCashFlow) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateCashFlow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateCashFlow(val *AffiliateCashFlow) *NullableAffiliateCashFlow {
	return &NullableAffiliateCashFlow{value: val, isSet: true}
}

func (v NullableAffiliateCashFlow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateCashFlow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


