/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type Portfolio struct {
	UserId string `json:"user_id,omitempty"`
	Position map[string]map[string]map[string]Position `json:"position,omitempty"`
	NetStablecoinEquivalence *TransformedAssets `json:"net_stablecoin_equivalence,omitempty"`
}
