/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the ModuleBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModuleBalance{}

// ModuleBalance struct for ModuleBalance
type ModuleBalance struct {
	AssetId *string `json:"asset_id,omitempty"`
	Seq *int32 `json:"seq,omitempty"`
	// The available balance in the module for this asset
	Available *string `json:"available,omitempty"`
	// The total amount supplied to the module for this asset
	Supplied *string `json:"supplied,omitempty"`
	// Assets minted by virtual-borrowing, but not yet repaid
	Virtual *string `json:"virtual,omitempty"`
	// The total amount borrowed from the supplied but not yet repaid
	Borrowed *string `json:"borrowed,omitempty"`
}

// NewModuleBalance instantiates a new ModuleBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModuleBalance() *ModuleBalance {
	this := ModuleBalance{}
	return &this
}

// NewModuleBalanceWithDefaults instantiates a new ModuleBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModuleBalanceWithDefaults() *ModuleBalance {
	this := ModuleBalance{}
	return &this
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *ModuleBalance) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleBalance) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *ModuleBalance) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *ModuleBalance) SetAssetId(v string) {
	o.AssetId = &v
}

// GetSeq returns the Seq field value if set, zero value otherwise.
func (o *ModuleBalance) GetSeq() int32 {
	if o == nil || IsNil(o.Seq) {
		var ret int32
		return ret
	}
	return *o.Seq
}

// GetSeqOk returns a tuple with the Seq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleBalance) GetSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.Seq) {
		return nil, false
	}
	return o.Seq, true
}

// HasSeq returns a boolean if a field has been set.
func (o *ModuleBalance) HasSeq() bool {
	if o != nil && !IsNil(o.Seq) {
		return true
	}

	return false
}

// SetSeq gets a reference to the given int32 and assigns it to the Seq field.
func (o *ModuleBalance) SetSeq(v int32) {
	o.Seq = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *ModuleBalance) GetAvailable() string {
	if o == nil || IsNil(o.Available) {
		var ret string
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleBalance) GetAvailableOk() (*string, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *ModuleBalance) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given string and assigns it to the Available field.
func (o *ModuleBalance) SetAvailable(v string) {
	o.Available = &v
}

// GetSupplied returns the Supplied field value if set, zero value otherwise.
func (o *ModuleBalance) GetSupplied() string {
	if o == nil || IsNil(o.Supplied) {
		var ret string
		return ret
	}
	return *o.Supplied
}

// GetSuppliedOk returns a tuple with the Supplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleBalance) GetSuppliedOk() (*string, bool) {
	if o == nil || IsNil(o.Supplied) {
		return nil, false
	}
	return o.Supplied, true
}

// HasSupplied returns a boolean if a field has been set.
func (o *ModuleBalance) HasSupplied() bool {
	if o != nil && !IsNil(o.Supplied) {
		return true
	}

	return false
}

// SetSupplied gets a reference to the given string and assigns it to the Supplied field.
func (o *ModuleBalance) SetSupplied(v string) {
	o.Supplied = &v
}

// GetVirtual returns the Virtual field value if set, zero value otherwise.
func (o *ModuleBalance) GetVirtual() string {
	if o == nil || IsNil(o.Virtual) {
		var ret string
		return ret
	}
	return *o.Virtual
}

// GetVirtualOk returns a tuple with the Virtual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleBalance) GetVirtualOk() (*string, bool) {
	if o == nil || IsNil(o.Virtual) {
		return nil, false
	}
	return o.Virtual, true
}

// HasVirtual returns a boolean if a field has been set.
func (o *ModuleBalance) HasVirtual() bool {
	if o != nil && !IsNil(o.Virtual) {
		return true
	}

	return false
}

// SetVirtual gets a reference to the given string and assigns it to the Virtual field.
func (o *ModuleBalance) SetVirtual(v string) {
	o.Virtual = &v
}

// GetBorrowed returns the Borrowed field value if set, zero value otherwise.
func (o *ModuleBalance) GetBorrowed() string {
	if o == nil || IsNil(o.Borrowed) {
		var ret string
		return ret
	}
	return *o.Borrowed
}

// GetBorrowedOk returns a tuple with the Borrowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleBalance) GetBorrowedOk() (*string, bool) {
	if o == nil || IsNil(o.Borrowed) {
		return nil, false
	}
	return o.Borrowed, true
}

// HasBorrowed returns a boolean if a field has been set.
func (o *ModuleBalance) HasBorrowed() bool {
	if o != nil && !IsNil(o.Borrowed) {
		return true
	}

	return false
}

// SetBorrowed gets a reference to the given string and assigns it to the Borrowed field.
func (o *ModuleBalance) SetBorrowed(v string) {
	o.Borrowed = &v
}

func (o ModuleBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModuleBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	if !IsNil(o.Seq) {
		toSerialize["seq"] = o.Seq
	}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Supplied) {
		toSerialize["supplied"] = o.Supplied
	}
	if !IsNil(o.Virtual) {
		toSerialize["virtual"] = o.Virtual
	}
	if !IsNil(o.Borrowed) {
		toSerialize["borrowed"] = o.Borrowed
	}
	return toSerialize, nil
}

type NullableModuleBalance struct {
	value *ModuleBalance
	isSet bool
}

func (v NullableModuleBalance) Get() *ModuleBalance {
	return v.value
}

func (v *NullableModuleBalance) Set(val *ModuleBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableModuleBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableModuleBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModuleBalance(val *ModuleBalance) *NullableModuleBalance {
	return &NullableModuleBalance{value: val, isSet: true}
}

func (v NullableModuleBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModuleBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


