/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClaimLeverageAccruedInterestReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimLeverageAccruedInterestReq{}

// ClaimLeverageAccruedInterestReq struct for ClaimLeverageAccruedInterestReq
type ClaimLeverageAccruedInterestReq struct {
	PositionId string `json:"position_id"`
	AssetId string `json:"asset_id"`
	Quantity string `json:"quantity"`
}

type _ClaimLeverageAccruedInterestReq ClaimLeverageAccruedInterestReq

// NewClaimLeverageAccruedInterestReq instantiates a new ClaimLeverageAccruedInterestReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimLeverageAccruedInterestReq(positionId string, assetId string, quantity string) *ClaimLeverageAccruedInterestReq {
	this := ClaimLeverageAccruedInterestReq{}
	this.PositionId = positionId
	this.AssetId = assetId
	this.Quantity = quantity
	return &this
}

// NewClaimLeverageAccruedInterestReqWithDefaults instantiates a new ClaimLeverageAccruedInterestReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimLeverageAccruedInterestReqWithDefaults() *ClaimLeverageAccruedInterestReq {
	this := ClaimLeverageAccruedInterestReq{}
	return &this
}

// GetPositionId returns the PositionId field value
func (o *ClaimLeverageAccruedInterestReq) GetPositionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterestReq) GetPositionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionId, true
}

// SetPositionId sets field value
func (o *ClaimLeverageAccruedInterestReq) SetPositionId(v string) {
	o.PositionId = v
}

// GetAssetId returns the AssetId field value
func (o *ClaimLeverageAccruedInterestReq) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterestReq) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *ClaimLeverageAccruedInterestReq) SetAssetId(v string) {
	o.AssetId = v
}

// GetQuantity returns the Quantity field value
func (o *ClaimLeverageAccruedInterestReq) GetQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *ClaimLeverageAccruedInterestReq) GetQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *ClaimLeverageAccruedInterestReq) SetQuantity(v string) {
	o.Quantity = v
}

func (o ClaimLeverageAccruedInterestReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimLeverageAccruedInterestReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["position_id"] = o.PositionId
	toSerialize["asset_id"] = o.AssetId
	toSerialize["quantity"] = o.Quantity
	return toSerialize, nil
}

func (o *ClaimLeverageAccruedInterestReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"position_id",
		"asset_id",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimLeverageAccruedInterestReq := _ClaimLeverageAccruedInterestReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClaimLeverageAccruedInterestReq)

	if err != nil {
		return err
	}

	*o = ClaimLeverageAccruedInterestReq(varClaimLeverageAccruedInterestReq)

	return err
}

type NullableClaimLeverageAccruedInterestReq struct {
	value *ClaimLeverageAccruedInterestReq
	isSet bool
}

func (v NullableClaimLeverageAccruedInterestReq) Get() *ClaimLeverageAccruedInterestReq {
	return v.value
}

func (v *NullableClaimLeverageAccruedInterestReq) Set(val *ClaimLeverageAccruedInterestReq) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimLeverageAccruedInterestReq) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimLeverageAccruedInterestReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimLeverageAccruedInterestReq(val *ClaimLeverageAccruedInterestReq) *NullableClaimLeverageAccruedInterestReq {
	return &NullableClaimLeverageAccruedInterestReq{value: val, isSet: true}
}

func (v NullableClaimLeverageAccruedInterestReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimLeverageAccruedInterestReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


