/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type ModuleBalance struct {
	AssetId string `json:"asset_id,omitempty"`
	Seq int32 `json:"seq,omitempty"`
	// The available balance in the module for this asset
	Available string `json:"available,omitempty"`
	// The total amount supplied to the module for this asset
	Supplied string `json:"supplied,omitempty"`
	// Assets minted by virtual-borrowing, but not yet repaid
	Virtual string `json:"virtual,omitempty"`
	// The total amount borrowed from the supplied but not yet repaid
	Borrowed string `json:"borrowed,omitempty"`
}
