/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeverageInterestRateResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeverageInterestRateResponseEnvelope{}

// LeverageInterestRateResponseEnvelope struct for LeverageInterestRateResponseEnvelope
type LeverageInterestRateResponseEnvelope struct {
	Data *LeverageInterestRate `json:"data,omitempty"`
	// The error message. Present for error (non-2xx) responses.
	Error *string `json:"error,omitempty"`
	// Metadata about the response, including status code and trace information.
	Metadata Metadata `json:"metadata"`
}

type _LeverageInterestRateResponseEnvelope LeverageInterestRateResponseEnvelope

// NewLeverageInterestRateResponseEnvelope instantiates a new LeverageInterestRateResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeverageInterestRateResponseEnvelope(metadata Metadata) *LeverageInterestRateResponseEnvelope {
	this := LeverageInterestRateResponseEnvelope{}
	this.Metadata = metadata
	return &this
}

// NewLeverageInterestRateResponseEnvelopeWithDefaults instantiates a new LeverageInterestRateResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeverageInterestRateResponseEnvelopeWithDefaults() *LeverageInterestRateResponseEnvelope {
	this := LeverageInterestRateResponseEnvelope{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LeverageInterestRateResponseEnvelope) GetData() LeverageInterestRate {
	if o == nil || IsNil(o.Data) {
		var ret LeverageInterestRate
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeverageInterestRateResponseEnvelope) GetDataOk() (*LeverageInterestRate, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LeverageInterestRateResponseEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given LeverageInterestRate and assigns it to the Data field.
func (o *LeverageInterestRateResponseEnvelope) SetData(v LeverageInterestRate) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *LeverageInterestRateResponseEnvelope) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeverageInterestRateResponseEnvelope) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *LeverageInterestRateResponseEnvelope) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *LeverageInterestRateResponseEnvelope) SetError(v string) {
	o.Error = &v
}

// GetMetadata returns the Metadata field value
func (o *LeverageInterestRateResponseEnvelope) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *LeverageInterestRateResponseEnvelope) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *LeverageInterestRateResponseEnvelope) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o LeverageInterestRateResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeverageInterestRateResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *LeverageInterestRateResponseEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeverageInterestRateResponseEnvelope := _LeverageInterestRateResponseEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeverageInterestRateResponseEnvelope)

	if err != nil {
		return err
	}

	*o = LeverageInterestRateResponseEnvelope(varLeverageInterestRateResponseEnvelope)

	return err
}

type NullableLeverageInterestRateResponseEnvelope struct {
	value *LeverageInterestRateResponseEnvelope
	isSet bool
}

func (v NullableLeverageInterestRateResponseEnvelope) Get() *LeverageInterestRateResponseEnvelope {
	return v.value
}

func (v *NullableLeverageInterestRateResponseEnvelope) Set(val *LeverageInterestRateResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableLeverageInterestRateResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableLeverageInterestRateResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeverageInterestRateResponseEnvelope(val *LeverageInterestRateResponseEnvelope) *NullableLeverageInterestRateResponseEnvelope {
	return &NullableLeverageInterestRateResponseEnvelope{value: val, isSet: true}
}

func (v NullableLeverageInterestRateResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeverageInterestRateResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


