/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the UserCouponPaymentsResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCouponPaymentsResponseData{}

// UserCouponPaymentsResponseData struct for UserCouponPaymentsResponseData
type UserCouponPaymentsResponseData struct {
	CouponPayments []UserCouponPayment `json:"coupon_payments,omitempty"`
	SummaryByAsset []UserCouponPaymentAssetSummary `json:"summary_by_asset,omitempty"`
}

// NewUserCouponPaymentsResponseData instantiates a new UserCouponPaymentsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCouponPaymentsResponseData() *UserCouponPaymentsResponseData {
	this := UserCouponPaymentsResponseData{}
	return &this
}

// NewUserCouponPaymentsResponseDataWithDefaults instantiates a new UserCouponPaymentsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCouponPaymentsResponseDataWithDefaults() *UserCouponPaymentsResponseData {
	this := UserCouponPaymentsResponseData{}
	return &this
}

// GetCouponPayments returns the CouponPayments field value if set, zero value otherwise.
func (o *UserCouponPaymentsResponseData) GetCouponPayments() []UserCouponPayment {
	if o == nil || IsNil(o.CouponPayments) {
		var ret []UserCouponPayment
		return ret
	}
	return o.CouponPayments
}

// GetCouponPaymentsOk returns a tuple with the CouponPayments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCouponPaymentsResponseData) GetCouponPaymentsOk() ([]UserCouponPayment, bool) {
	if o == nil || IsNil(o.CouponPayments) {
		return nil, false
	}
	return o.CouponPayments, true
}

// HasCouponPayments returns a boolean if a field has been set.
func (o *UserCouponPaymentsResponseData) HasCouponPayments() bool {
	if o != nil && !IsNil(o.CouponPayments) {
		return true
	}

	return false
}

// SetCouponPayments gets a reference to the given []UserCouponPayment and assigns it to the CouponPayments field.
func (o *UserCouponPaymentsResponseData) SetCouponPayments(v []UserCouponPayment) {
	o.CouponPayments = v
}

// GetSummaryByAsset returns the SummaryByAsset field value if set, zero value otherwise.
func (o *UserCouponPaymentsResponseData) GetSummaryByAsset() []UserCouponPaymentAssetSummary {
	if o == nil || IsNil(o.SummaryByAsset) {
		var ret []UserCouponPaymentAssetSummary
		return ret
	}
	return o.SummaryByAsset
}

// GetSummaryByAssetOk returns a tuple with the SummaryByAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCouponPaymentsResponseData) GetSummaryByAssetOk() ([]UserCouponPaymentAssetSummary, bool) {
	if o == nil || IsNil(o.SummaryByAsset) {
		return nil, false
	}
	return o.SummaryByAsset, true
}

// HasSummaryByAsset returns a boolean if a field has been set.
func (o *UserCouponPaymentsResponseData) HasSummaryByAsset() bool {
	if o != nil && !IsNil(o.SummaryByAsset) {
		return true
	}

	return false
}

// SetSummaryByAsset gets a reference to the given []UserCouponPaymentAssetSummary and assigns it to the SummaryByAsset field.
func (o *UserCouponPaymentsResponseData) SetSummaryByAsset(v []UserCouponPaymentAssetSummary) {
	o.SummaryByAsset = v
}

func (o UserCouponPaymentsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCouponPaymentsResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CouponPayments) {
		toSerialize["coupon_payments"] = o.CouponPayments
	}
	if !IsNil(o.SummaryByAsset) {
		toSerialize["summary_by_asset"] = o.SummaryByAsset
	}
	return toSerialize, nil
}

type NullableUserCouponPaymentsResponseData struct {
	value *UserCouponPaymentsResponseData
	isSet bool
}

func (v NullableUserCouponPaymentsResponseData) Get() *UserCouponPaymentsResponseData {
	return v.value
}

func (v *NullableUserCouponPaymentsResponseData) Set(val *UserCouponPaymentsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCouponPaymentsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCouponPaymentsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCouponPaymentsResponseData(val *UserCouponPaymentsResponseData) *NullableUserCouponPaymentsResponseData {
	return &NullableUserCouponPaymentsResponseData{value: val, isSet: true}
}

func (v NullableUserCouponPaymentsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCouponPaymentsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


