/*
DORA

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doraclient

import (
	"encoding/json"
)

// checks if the PLAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PLAsset{}

// PLAsset struct for PLAsset
type PLAsset struct {
	// The symbol of the asset
	Symbol *string `json:"symbol,omitempty"`
	// The side of the position (LONG or SHORT)
	Side *string `json:"side,omitempty"`
	// The average entry price of the position
	AvgEntryPrice *float64 `json:"avg_entry_price,omitempty"`
	// The current mark price for the asset to calculate daily PL. This is usually the close price of the previous day
	MarkPrice *float64 `json:"mark_price,omitempty"`
	// The liquidation price of the position
	LiquidationPrice *float64 `json:"liquidation_price,omitempty"`
	// The available quantity in units of the asset
	Available *float64 `json:"available,omitempty"`
	// The borrowed quantity in units of the asset
	Borrowed *float64 `json:"borrowed,omitempty"`
	Margin *Margin `json:"margin,omitempty"`
	// The unrealized profit or loss of the position
	UnrealizedPl *float64 `json:"unrealized_pl,omitempty"`
	// The leverage limit for the position
	LeverageLimit *float64 `json:"leverage_limit,omitempty"`
	// The take profit price set for the position, if any
	Tp *float64 `json:"tp,omitempty"`
	// The stop loss price set for the position, if any
	Sl *float64 `json:"sl,omitempty"`
}

// NewPLAsset instantiates a new PLAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPLAsset() *PLAsset {
	this := PLAsset{}
	return &this
}

// NewPLAssetWithDefaults instantiates a new PLAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPLAssetWithDefaults() *PLAsset {
	this := PLAsset{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *PLAsset) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *PLAsset) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *PLAsset) SetSymbol(v string) {
	o.Symbol = &v
}

// GetSide returns the Side field value if set, zero value otherwise.
func (o *PLAsset) GetSide() string {
	if o == nil || IsNil(o.Side) {
		var ret string
		return ret
	}
	return *o.Side
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetSideOk() (*string, bool) {
	if o == nil || IsNil(o.Side) {
		return nil, false
	}
	return o.Side, true
}

// HasSide returns a boolean if a field has been set.
func (o *PLAsset) HasSide() bool {
	if o != nil && !IsNil(o.Side) {
		return true
	}

	return false
}

// SetSide gets a reference to the given string and assigns it to the Side field.
func (o *PLAsset) SetSide(v string) {
	o.Side = &v
}

// GetAvgEntryPrice returns the AvgEntryPrice field value if set, zero value otherwise.
func (o *PLAsset) GetAvgEntryPrice() float64 {
	if o == nil || IsNil(o.AvgEntryPrice) {
		var ret float64
		return ret
	}
	return *o.AvgEntryPrice
}

// GetAvgEntryPriceOk returns a tuple with the AvgEntryPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetAvgEntryPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.AvgEntryPrice) {
		return nil, false
	}
	return o.AvgEntryPrice, true
}

// HasAvgEntryPrice returns a boolean if a field has been set.
func (o *PLAsset) HasAvgEntryPrice() bool {
	if o != nil && !IsNil(o.AvgEntryPrice) {
		return true
	}

	return false
}

// SetAvgEntryPrice gets a reference to the given float64 and assigns it to the AvgEntryPrice field.
func (o *PLAsset) SetAvgEntryPrice(v float64) {
	o.AvgEntryPrice = &v
}

// GetMarkPrice returns the MarkPrice field value if set, zero value otherwise.
func (o *PLAsset) GetMarkPrice() float64 {
	if o == nil || IsNil(o.MarkPrice) {
		var ret float64
		return ret
	}
	return *o.MarkPrice
}

// GetMarkPriceOk returns a tuple with the MarkPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetMarkPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.MarkPrice) {
		return nil, false
	}
	return o.MarkPrice, true
}

// HasMarkPrice returns a boolean if a field has been set.
func (o *PLAsset) HasMarkPrice() bool {
	if o != nil && !IsNil(o.MarkPrice) {
		return true
	}

	return false
}

// SetMarkPrice gets a reference to the given float64 and assigns it to the MarkPrice field.
func (o *PLAsset) SetMarkPrice(v float64) {
	o.MarkPrice = &v
}

// GetLiquidationPrice returns the LiquidationPrice field value if set, zero value otherwise.
func (o *PLAsset) GetLiquidationPrice() float64 {
	if o == nil || IsNil(o.LiquidationPrice) {
		var ret float64
		return ret
	}
	return *o.LiquidationPrice
}

// GetLiquidationPriceOk returns a tuple with the LiquidationPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetLiquidationPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.LiquidationPrice) {
		return nil, false
	}
	return o.LiquidationPrice, true
}

// HasLiquidationPrice returns a boolean if a field has been set.
func (o *PLAsset) HasLiquidationPrice() bool {
	if o != nil && !IsNil(o.LiquidationPrice) {
		return true
	}

	return false
}

// SetLiquidationPrice gets a reference to the given float64 and assigns it to the LiquidationPrice field.
func (o *PLAsset) SetLiquidationPrice(v float64) {
	o.LiquidationPrice = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *PLAsset) GetAvailable() float64 {
	if o == nil || IsNil(o.Available) {
		var ret float64
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetAvailableOk() (*float64, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *PLAsset) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given float64 and assigns it to the Available field.
func (o *PLAsset) SetAvailable(v float64) {
	o.Available = &v
}

// GetBorrowed returns the Borrowed field value if set, zero value otherwise.
func (o *PLAsset) GetBorrowed() float64 {
	if o == nil || IsNil(o.Borrowed) {
		var ret float64
		return ret
	}
	return *o.Borrowed
}

// GetBorrowedOk returns a tuple with the Borrowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetBorrowedOk() (*float64, bool) {
	if o == nil || IsNil(o.Borrowed) {
		return nil, false
	}
	return o.Borrowed, true
}

// HasBorrowed returns a boolean if a field has been set.
func (o *PLAsset) HasBorrowed() bool {
	if o != nil && !IsNil(o.Borrowed) {
		return true
	}

	return false
}

// SetBorrowed gets a reference to the given float64 and assigns it to the Borrowed field.
func (o *PLAsset) SetBorrowed(v float64) {
	o.Borrowed = &v
}

// GetMargin returns the Margin field value if set, zero value otherwise.
func (o *PLAsset) GetMargin() Margin {
	if o == nil || IsNil(o.Margin) {
		var ret Margin
		return ret
	}
	return *o.Margin
}

// GetMarginOk returns a tuple with the Margin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetMarginOk() (*Margin, bool) {
	if o == nil || IsNil(o.Margin) {
		return nil, false
	}
	return o.Margin, true
}

// HasMargin returns a boolean if a field has been set.
func (o *PLAsset) HasMargin() bool {
	if o != nil && !IsNil(o.Margin) {
		return true
	}

	return false
}

// SetMargin gets a reference to the given Margin and assigns it to the Margin field.
func (o *PLAsset) SetMargin(v Margin) {
	o.Margin = &v
}

// GetUnrealizedPl returns the UnrealizedPl field value if set, zero value otherwise.
func (o *PLAsset) GetUnrealizedPl() float64 {
	if o == nil || IsNil(o.UnrealizedPl) {
		var ret float64
		return ret
	}
	return *o.UnrealizedPl
}

// GetUnrealizedPlOk returns a tuple with the UnrealizedPl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetUnrealizedPlOk() (*float64, bool) {
	if o == nil || IsNil(o.UnrealizedPl) {
		return nil, false
	}
	return o.UnrealizedPl, true
}

// HasUnrealizedPl returns a boolean if a field has been set.
func (o *PLAsset) HasUnrealizedPl() bool {
	if o != nil && !IsNil(o.UnrealizedPl) {
		return true
	}

	return false
}

// SetUnrealizedPl gets a reference to the given float64 and assigns it to the UnrealizedPl field.
func (o *PLAsset) SetUnrealizedPl(v float64) {
	o.UnrealizedPl = &v
}

// GetLeverageLimit returns the LeverageLimit field value if set, zero value otherwise.
func (o *PLAsset) GetLeverageLimit() float64 {
	if o == nil || IsNil(o.LeverageLimit) {
		var ret float64
		return ret
	}
	return *o.LeverageLimit
}

// GetLeverageLimitOk returns a tuple with the LeverageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetLeverageLimitOk() (*float64, bool) {
	if o == nil || IsNil(o.LeverageLimit) {
		return nil, false
	}
	return o.LeverageLimit, true
}

// HasLeverageLimit returns a boolean if a field has been set.
func (o *PLAsset) HasLeverageLimit() bool {
	if o != nil && !IsNil(o.LeverageLimit) {
		return true
	}

	return false
}

// SetLeverageLimit gets a reference to the given float64 and assigns it to the LeverageLimit field.
func (o *PLAsset) SetLeverageLimit(v float64) {
	o.LeverageLimit = &v
}

// GetTp returns the Tp field value if set, zero value otherwise.
func (o *PLAsset) GetTp() float64 {
	if o == nil || IsNil(o.Tp) {
		var ret float64
		return ret
	}
	return *o.Tp
}

// GetTpOk returns a tuple with the Tp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetTpOk() (*float64, bool) {
	if o == nil || IsNil(o.Tp) {
		return nil, false
	}
	return o.Tp, true
}

// HasTp returns a boolean if a field has been set.
func (o *PLAsset) HasTp() bool {
	if o != nil && !IsNil(o.Tp) {
		return true
	}

	return false
}

// SetTp gets a reference to the given float64 and assigns it to the Tp field.
func (o *PLAsset) SetTp(v float64) {
	o.Tp = &v
}

// GetSl returns the Sl field value if set, zero value otherwise.
func (o *PLAsset) GetSl() float64 {
	if o == nil || IsNil(o.Sl) {
		var ret float64
		return ret
	}
	return *o.Sl
}

// GetSlOk returns a tuple with the Sl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PLAsset) GetSlOk() (*float64, bool) {
	if o == nil || IsNil(o.Sl) {
		return nil, false
	}
	return o.Sl, true
}

// HasSl returns a boolean if a field has been set.
func (o *PLAsset) HasSl() bool {
	if o != nil && !IsNil(o.Sl) {
		return true
	}

	return false
}

// SetSl gets a reference to the given float64 and assigns it to the Sl field.
func (o *PLAsset) SetSl(v float64) {
	o.Sl = &v
}

func (o PLAsset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PLAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Side) {
		toSerialize["side"] = o.Side
	}
	if !IsNil(o.AvgEntryPrice) {
		toSerialize["avg_entry_price"] = o.AvgEntryPrice
	}
	if !IsNil(o.MarkPrice) {
		toSerialize["mark_price"] = o.MarkPrice
	}
	if !IsNil(o.LiquidationPrice) {
		toSerialize["liquidation_price"] = o.LiquidationPrice
	}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Borrowed) {
		toSerialize["borrowed"] = o.Borrowed
	}
	if !IsNil(o.Margin) {
		toSerialize["margin"] = o.Margin
	}
	if !IsNil(o.UnrealizedPl) {
		toSerialize["unrealized_pl"] = o.UnrealizedPl
	}
	if !IsNil(o.LeverageLimit) {
		toSerialize["leverage_limit"] = o.LeverageLimit
	}
	if !IsNil(o.Tp) {
		toSerialize["tp"] = o.Tp
	}
	if !IsNil(o.Sl) {
		toSerialize["sl"] = o.Sl
	}
	return toSerialize, nil
}

type NullablePLAsset struct {
	value *PLAsset
	isSet bool
}

func (v NullablePLAsset) Get() *PLAsset {
	return v.value
}

func (v *NullablePLAsset) Set(val *PLAsset) {
	v.value = val
	v.isSet = true
}

func (v NullablePLAsset) IsSet() bool {
	return v.isSet
}

func (v *NullablePLAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePLAsset(val *PLAsset) *NullablePLAsset {
	return &NullablePLAsset{value: val, isSet: true}
}

func (v NullablePLAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePLAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


