/*
 * DORA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package doraclient

type LiquidityRequest struct {
	OrderBookId string `json:"order_book_id,omitempty"`
	PositionId string `json:"position_id,omitempty"`
	Quantity string `json:"quantity,omitempty"`
}
